### ISSUE TITLE
Consider adding coveralls configuration

### ISSUE THREAD

**Issue by aalmiray** [asciidoctor/asciidoctor-maven-plugin#107]
This way we can keep track of code coverage over time.

**Comment by wimdeblauwe** [comment]
Should this issue not be fixed as there is a code coverage badge visible now?

**Comment by LightGuard** [comment]
I believe so.

On Fri, Jan 30, 2015 at 4:34 PM, wimdeblauwe <notifications@github.com>
wrote:

> Should this issue not be fixed as there is a code coverage badge visible
> now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/107#issuecomment-72289421>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by abelsromero** [comment]
Let's close it then :+1:

**Comment by mojavelinux** [comment]
:+1:
