### ISSUE TITLE
'docdir' not correct when building a multimodule site 

### ISSUE THREAD

**Issue by domgold** [asciidoctor/asciidoctor-maven-plugin#133]
Using the site plugin, in a multimodule build, the `docdir` attributes corresponds to the basedir of the maven build.

With test.adoc

```
= Test

{docdir}

```

```
  └───parent
      ├───moduleA
      │   └───src/site/asciidoc
      │       └───test.adoc
      └───moduleB
```

When executing the build from the root/ parent as a multi-module build, `docdir` becomes `path/to/parent`.
When building only the module, `docdir` becomes `path/to/parent/moduleA`.

**Comment by abelsromero** [comment]
Can't say exactly what made the change, but with latest plugin version 2.1.0 this seems corrected.

Just created a project with a 2 sub-module + sources in root.
All of them display `{docdir}` attribute.
All show the correct source of the file. Note the attribute is derived from base_dir, so files under sub-directories show the root path for that project.
