### ISSUE TITLE
Chunked backed

### ISSUE THREAD

**Issue by woj-tek** [asciidoctor/asciidoctor-maven-plugin#135]
Hi,
I'm just starting with AsciiDoc, AsciiDoctor and maven plugin for the latter.

Is it possible to have 'chunked' output in asciidoctor-maven-plugin?

After digging a bit - if my understanding is correct, possible backends available in asciidoctor-maven-plugin depends on outputs available in asciidoctor itself - is that correct? Therefore after https://github.com/asciidoctor/asciidoctor/issues/626 being implemented it should be available without modification to asciidoctor-maven-plugin itself?

**Comment by abelsromero** [comment]
No longer relevant. Solution depends in Asciidoctor core components and there are alternatives like https://github.com/owenh000/asciidoctor-multipage

**Comment by woj-tek** [comment]
> Solution depends in Asciidoctor core components

What do you mean? From what I can see, asciidoctor (core) doesn't support chunked output: https://asciidoctor.org/docs/convert-documents/#selecting-an-output-format

Supplemental converters (https://asciidoctor.org/docs/#supplemental-converters) only list some but nothing mentions "chunked". From what I've read regarding newer asciidoctor release, there is nothing particularly geared towards "chunked" output.

On the other hand, there is a "asciidoctor-multipage" (it's referenced here: https://github.com/asciidoctor/asciidoctor/issues/626) but the multipage converter (https://github.com/owenh000/asciidoctor-multipage) is limited only to asciidoctor in the exact version of v1.5.7.1 (https://github.com/owenh000/asciidoctor-multipage/issues/2), which was released 2 years ago (and I'm not sure it would be possible to use it with asciidoctor-maven-plugin tbh).

**Comment by mojavelinux** [comment]
The path forward would to be evolve the asciidoctor-multipage converter. Where it is limited by the capabilities of core, we can work to improve core. Regardless, this is not specifically a Maven plugin issue, IMO.

**Comment by woj-tek** [comment]
OK, maven plugin uses asciidoctorj, which uses asciidoctor itself (more or less directly) so in the plugin it's possible to use extensions/converters - correct?

Regarding limitations of core and asciidoctor-multipage -- how those could be addressed? Is there any plan? How can one contribute? :-)

**Comment by abelsromero** [comment]
> OK, maven plugin uses asciidoctorj, which uses asciidoctor itself (more or less directly) so in the plugin it's possible to use extensions/converters - correct?

Is exactly as you say!

Regarding using a extension. It seems to me `asciidoctor-multipage` should work like revealjs integration, with the caveat (other than asciidoctor version) that youll need to download the gem manually because it's not in rubygems.
- Here is a example of download plugin https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoctor-pdf-cjk-example/pom.xml
- Here is example of revealjs, see how <requires> and the <backend> are set: https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-revealjs-example/pom.xml.

If you have problems with it, if you can share a test repo we can work on it.

**Comment by woj-tek** [comment]
Thanks, I'll play with it.

Though, when I asked about "how can one contribute" I was asking more how to make `asciidoctor-multipage` compatible with the latest asciidoctor(j) :-)

**Comment by abelsromero** [comment]
> Though, when I asked about "how can one contribute" I was asking more how to make `asciidoctor-multipage` compatible with the latest asciidoctor(j) :-)

That's something you should addreess with the author. The beginning README points to several issues that contain information.

**Comment by mojavelinux** [comment]
It seems like the author is looking for a new maintainer (https://github.com/owenh000/asciidoctor-multipage/issues/2). If someone volunteers, I'm willing to work with Owen to get that person set up. If the project is well-maintained, we can bring it into the asciidoctor organization to give it more exposure. Please reach out in https://gitter.im/asciidoctor/asciidoctor if interested.
