### ISSUE TITLE
Allow to set java extensions

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#146]
Currently there’s no way to integrate java extensions ([asciidoctorj#extension-api](https://github.com/asciidoctor/asciidoctorj#extension-api)) in the maven plugin. So, my proposal is to include a new tag called `<processors>` (because there’s already an extension tag) to allow setting one or more  extensions in the pom.

Currently, there're 3 ways to register a extension, the first 2 (passing as String a fully qualified class and passing a Class object of the extension) are easy. For the 3rd one (passing an instance of the extension object) I’m thinking to allow writing Groovy code in the pom.xml itself of being able to reference a groovy script. This way it would be also possible to include inline extensions with the DSL.

The only problem I see is that the Groovy option may be missused for other purpouses, but otoh this provides a method to customize the build in ways that we cannot provide (see #144).

What do you think?

cc @lordofthejars

**Comment by LightGuard** [comment]
This hasn't been done yet? I thought it had. First two are golden... the
other, I'm a bit hesitant with. As we've seen in some other threads things
get misused easily and then they create bugs about the misuse :) I'd rather
not have the plugin do more than is absolutely necessary to get things
going. There's much less chance of things going wrong that way.

On Thu, Jan 22, 2015 at 12:23 AM, Abel Salgado Romero <
notifications@github.com> wrote:

> Currently there’s no way to integrate java extensions (
> asciidoctorj#extension-api
> <https://github.com/asciidoctor/asciidoctorj#extension-api>) in the maven
> plugin. So, my proposal is to include a new tag called <processors>
> (because there’s already an extension tag) to allow setting one or more
> extensions in the pom.
>
> Currently, there're 3 ways to register a extension, the first 2 (passing
> as String a fully qualified class and passing a Class object of the
> extension) are easy. For the 3rd one (passing an instance of the extension
> object) I’m thinking to allow writing Groovy code in the pom.xml itself of
> being able to reference a groovy script. This way it would be also possible
> to include inline extensions with the DSL.
>
> The only problem I see is that the Groovy option may be missused for other
> purpouses, but otoh this provides a method to customize the build in ways
> that we cannot provide (see #144
> <https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/144>).
>
> What do you think?
>
> cc @lordofthejars <https://github.com/lordofthejars>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/146>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by abelsromero** [comment]
I think we are agree that it opens some dangerous doors and this should be considered. However, in the end, even if we forbid option 3 nothing stops you from doing the same misuses inside the processos itself. Afterall, once you allow to inject a class with custom code, anything can be done inside.
That's my main point in fact, since you cannot avoid it, at least don't make it harder.

**Comment by LightGuard** [comment]
Hm. Not sure where I sit with option 3 still. Worth thinking about.

On Thu, Jan 22, 2015 at 11:24 AM, Abel Salgado Romero <
notifications@github.com> wrote:

> I think we are agree that it opens some dangerous doors and this should be
> considered. However, in the end, even if we forbid option 3 nothing stops
> you from doing the same misuses inside the processos itself. Afterall, once
> you allow to inject a class with custom code, anything can be done inside.
> That's my main point in fact, since you cannot avoid it, at least don't
> make it harder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/146#issuecomment-71070806>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by mojavelinux** [comment]
> First two are golden... the other, I'm a bit hesitant with.

I'm with @LightGuard on this one. Let's just encourage the best practice of registering a processor by it's implementation class. If more is needed, then the user can use an extension as an entry point to register additional extensions. This is consistent with the models in CDI and Arquillian that have been extremely successful and proven.

Keep in mind that it's also possible to register an extension by putting a service loader file on the classpath. That's technically the most correct way to do it, though I do like the added control of being able to register an extension via the Maven configuration so it can be linked to profiles and the like.

Perhaps we should schedule this for 1.5.3?

**Comment by abelsromero** [comment]
Undestood.

> Perhaps we should schedule this for 1.5.3?

It's extremely easy and this is my top priority right now because I need it for a personal thing, so it's not a problem.

**Comment by mojavelinux** [comment]
:+1:
