### ISSUE TITLE
Update Maven properties documentation on how to set the Maven project version as the revision

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-maven-plugin#147]
I just lost quite some time trying to set the Maven project version in the header and footer of the HTML output. The section on it (https://github.com/asciidoctor/asciidoctor-maven-plugin#passing-pom-properties) does not mention that you have to use this construct:

`:revnumber: {project-version}`

to make it work. Would be great to add a TIP or NOTE there since it seems extremely likely that other people will use this as well. Luckily I found it in [this discussion](http://discuss.asciidoctor.org/Maven-plugin-a-way-to-incorporate-a-maven-property-in-asciidoc-td992.html#a2434).

**Comment by abelsromero** [comment]
That's not a bad idea, maybe we could add some NOTE section explaninf this special case.
Also, I'd be nice to have a unit test to validate it, from the forum post it seems to me that this is something that could change someday.

what do you think?

**Comment by wimdeblauwe** [comment]
I have created a pull request that updates the readme and adds a unit test for it.

**Comment by wimdeblauwe** [comment]
I am just noticing right now that the documentation is not using `project-version` but `docVersion`. Would it not be better to change `docVersion` to `project-version` in the readme as well so it is the same as in the unit test?

**Comment by abelsromero** [comment]
That one slipt under my nose, sorry.
I'd rather replace `{project-version}` by `{docVersion}` in the README to make more clear how the replacement is done.
About the test, I don't see any problem with it as long as it serves it's pupouse, i'd leave that to you.
