### ISSUE TITLE
Provide an option to suffix generated file names with pom version

### ISSUE THREAD

**Issue by matdere** [asciidoctor/asciidoctor-maven-plugin#156]
Hi,

First of all, thank you so much for making me discover asciidoctor during Devoxx France last week. You guys changed the way I will manage documentation now ! 

To my point of view, it would be great to have the possibilité to add the POM version to the generated files. 
The idea is to give the possibilité to the user to choose automatically the documentation that correspond to the software version they have. 

For example the file name would be : **mysupersoft-0.9.7.RELEASE.html**

What do you think about it ?

**Comment by abelsromero** [comment]
Welcome Mathieu :smiley: 

This is not a bad idea, specially if you have several code branch (e.g. preview, stable, etc.) and you want to publish several versions of the documentation.
But I am not sure this fully solves the problem, specially when dealing with complex structures of documents with folders, images, css, etc. Also, browsing can be a bit complicated if the version is at the end of a folder structure in the file name. 
On the other hand, what do you think of setting the name in a folder? Currently, you can set the output folder in the `<configuration>` block in the following way:

```
<outputDirectory>target/generated-docs/${project.version}</outputDirectory>
```

What do you think?


PS: don't forget to check this https://github.com/asciidoctor/asciidoctor-maven-plugin#passing-pom-properties, to set the version in the document footer.

**Comment by matdere** [comment]
Hola Abel, 
Awesome !!!! This is even better ! 
Thanks !

**Comment by mojavelinux** [comment]
> thank you so much for making me discover asciidoctor during Devoxx France last week. You guys changed the way I will manage documentation now !

Excellent! I'm so glad to hear that!

> Currently, you can set the output folder in the <configuration> block in the following way...

Great suggestion Abel! Perhaps this is something we could document in the README / user manual because I bet a lot of people would like to use it. Perhaps we can add a "Tips & Tricks" section.
