### ISSUE TITLE
Allow the source highlighter to be enabled in the site plugin

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-maven-plugin#160]
It should be possible to enable the source highlighter from the plugin configuration when using the site plugin.

This issue involves two parts:

1. An option for enabling the source highlighter (similar to the main plugin)
2. Ensure that the source highlighting works when enabled (any necessary styles are included)

As a workaround, you can enable the source highlighter by adding an explicit attribute in the document header.

**Comment by mojavelinux** [comment]
@paranoiabla, you mentioned you got this working in light of recent changes to the plugin. Could you elaborate?

**Comment by paranoiabla** [comment]
I'm using the `:source-highlighter: coderay` option in the header of each asciidoctor file. That seems to work. The drawback is that if you want to change it, you have to go through all the files and manually change the header.

**Comment by mojavelinux** [comment]
Is it possible to pass configuration to a Maven site module? If so, then we could pass that on to AsciidoctorJ.

**Comment by abelsromero** [comment]
> Is it possible to pass configuration to a Maven site module?

According to documentation you can add a site descriptor (site.xml in src/site) to customize the layout and other things ([ref](http://maven.apache.org/plugins/maven-site-plugin/examples/sitedescriptor.html)). Inside it you can add a section for custom properties `<custom>` http://maven.apache.org/plugins/maven-site-plugin/examples/sitedescriptor.html#Custom_Properties.

This could be an option, the thing is if we should support all the options from process-asciidoc mojo.

Also, so far I've only found a couple of example of how to recover custom properties and they use, either apache velocity scripts to directly generate the HTML, or some velocity api whose usage is not clear to me (https://github.com/andriusvelykis/reflow-maven-skin/blob/master/reflow-velocity-tools/src/main/java/lt/velykis/maven/skins/reflow/SkinConfigTool.java).
So, what I'm trying to say is that maybe getting the custom section to 'AsciidoctorParser' class won't be task for faint-hearted :smiley: Custom XML parsing is always an option, but I'm sure there must be a better way provided by the site-plugin tools.

**Comment by mojavelinux** [comment]
One other possibility is to have a convention to set Maven properties with a special prefix to pass options to Asciidoctor.

```
<asciidoc-site-source-highlighter>coderay</asciidoc-site-source-highlighter>
```

or we could stuff them all into a single property.

```
<maven-site-asciidoc-attributes>source-highlighter=coderay toc=macro</maven-site-asciidoc-attributes>
```

We should be able to read global attributes from the Maven plugin. It's not super clean, but it seems simpler than the alternatives thus far.

**Comment by tcollignon** [comment]
Hello,

the possiblity of using maven properties seem good for me, with this you can use every parameter of the maven plugin

Thanks for all answer guys, I will test this before having best solution

**Comment by tcollignon** [comment]
With  `:source-highlighter: coderay` it's better but not very beautiful. Did you add somme css style in maven resources ?
For example I have not found **CodeRay highlight** css class, this is my html maven site 

```
<div>
<pre class="CodeRay highlight">
<tt>
<span class="tag">&lt;pool-init&gt;</span>20<span class="tag">&lt;/pool-init&gt;</span>
<span class="tag">&lt;pool-min&gt;</span>20<span class="tag">&lt;/pool-min&gt;</span>
<span class="tag">&lt;pool-max&gt;</span>20<span class="tag">&lt;/pool-max&gt;</span>
</tt>
</pre>
</div>
```

for this input : 
```
[source,xml]
----
<pool-init>20</pool-init>
<pool-min>20</pool-min>
<pool-max>20</pool-max>
----
```

**Comment by mojavelinux** [comment]
You have two options. You can either grab the [CodeRay stylesheet](https://github.com/asciidoctor/asciidoctor/blob/master/data/stylesheets/coderay-asciidoctor.css) from the Asciidoctor repository and stick that into the template of your site or you can inline the styles using a second AsciiDoc attribute:

```
:coderay-css: style
```

**Comment by tcollignon** [comment]
Wonderful ! asciidoctor is very powerfull!
The last things still remain is the `<tt>` block who looks ugly, maybe it's the apache fluido skin :
`
tt {
    background-color: #fee9cc;
}
`

**Comment by mojavelinux** [comment]
I'm not sure what's adding the `<tt>` element. That shouldn't be happening. Are you sure that isn't getting added by Maven somehow?

**Comment by mojavelinux** [comment]
Aha. This may be something that's fixed by https://github.com/asciidoctor/asciidoctor-maven-plugin/commit/3dc576fe5a5e7efdc6544d8b561c43793383de70. Are you using the SNAPSHOT version? If not, this is a known issue because plexus messes with the output in a seriously nasty way right now.

**Comment by tcollignon** [comment]
Ohh I see, thank you, I will use a SNAPSHOT version until it will be releases.

**Comment by abelsromero** [comment]
I've been testing the idea of passing Maven properties and this does not work. Basically the Doxia Parser does not recognize the @Parameter notation in the attributes, which makes sense because [AsciidoctorParser](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/site/AsciidoctorParser.java) is not a plugin itself.

In the meantime I have sent a message to the user's mailing list, to see if they can offer some idea.

**Comment by ptahchiev** [comment]
Just a quick question here - is it possible to pass the properties as part of the `<systemPropertyVariables>`?

**Comment by mojavelinux** [comment]
> the Doxia Parser does not recognize the @Parameter notation in the attributes

The secret was to use the `@Requirement` annotation, which allows you to inject components available in the component tree into the class. If we inject the MavenProject, as shown here:

```java
@Requirement
protected MavenProject project;
```

then we can access the resolved configuration for the site plugin using the following call:

```
project.getGoalConfiguration("org.apache.maven.plugins", "maven-site-plugin", "site", "site");
```

With a little bit of work, it's possible to walk the DOM and extract the configuration we are interested in.
