### ISSUE TITLE
source-highlighter doesn't work

### ISSUE THREAD

**Issue by vicmosin** [asciidoctor/asciidoctor-maven-plugin#165]
I use this plugin as a part of [spring-restdocs](https://github.com/spring-projects/spring-restdocs).
Everything works fine except of code formatting - tried different options, but it looks similar. Take a look at attached file.

Config:
```
<plugin>
     <groupId>org.asciidoctor</groupId>
     <artifactId>asciidoctor-maven-plugin</artifactId>
     <version>1.5.2</version>
      <executions>
                <execution>
                     <id>generate-docs</id>
                    <phase>package</phase>
                    <goals>
                            <goal>process-asciidoc</goal>
                    </goals>
                     <configuration>
                            <backend>html</backend>
                            <doctype>book</doctype>
                            <attributes>
                                <generated>${project.build.directory}/generated-snippets</generated>
                            </attributes>
                    </configuration>
             </execution>
      </executions>
</plugin>
```

and code snippets are generated as `[source,http]`. Am I missing something?

![bildschirmfoto 2015-06-18 um 17 30 27](https://cloud.githubusercontent.com/assets/612207/8235009/cf9bf072-15df-11e5-898c-1ec274e20b3c.png)

**Comment by abelsromero** [comment]
Hi,
I fear code highlighting is not enabled by default, you must define what highlighter you want to use in the configuration with the attribute `sourceHighlighter` to get it working (see [here](https://github.com/asciidoctor/asciidoctor-maven-plugin#configuration-options) the details, and [here](https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-html-example/pom.xml) an example).

I run some tests `[source,http]` containint text and JSON syntax and only `highlightjs` supports `http`.
If you want to use the other option, which is `coderay`, you can try setting `[source,json]` but the coloring will be weird on the header tags.

_highlightjs + [source,http] example_
![captura](https://cloud.githubusercontent.com/assets/5781153/8236554/665134b0-15e9-11e5-9a59-1acecb30b04a.PNG)

**Comment by vicmosin** [comment]
Great, this works. But still there is no formatting..
I am talking about highlightjs + [source,http]

**Comment by abelsromero** [comment]
I'm not sure I understand what you mean by 'formatting', but I guess you need to indent the code like eclipse's [Ctrl+I] or [Ctrl+Shift+F] functions.
If that's the case, I'm sorry to say asciidoctor does not support this feature. Moreover, I tried to build it with a Java extension but it seems I cannot register it to the `source` block, it just won't trigger for it. If I rename the block it works thought.
Maybe @mojavelinux can provide some alterntive solution or an idea of how make the extension work...¿TreeProcessor or PreProcessor instead?

That's the test extesion I wrote:
```
public class SourceMacro extends BlockProcessor {

    @SuppressWarnings("serial")
    private static Map<String, Object> configs = new HashMap<String, Object>() {
        {
            put("contexts", Arrays.asList(":listing"));
            put("content_model", ":compound");
        }
    };

    public SourceMacro(String name, Map<String, Object> config) {
        super(name, configs);
    }

    @Override
    public Object process(AbstractBlock parent, Reader reader, Map<String, Object> attributes) {
        List<String> lines = reader.readLines();
        String text = new String();
        boolean foundBracket = false;
        for (String line : lines) {
            if (!foundBracket)
                foundBracket = line.contains("{");

            if (foundBracket) {
                text += line.trim();
                // do bracket counting here
            } else {
                // headers
                text += line.trim() + "\n";
            }
        }
        System.out.println(text);

        return createBlock(parent, "paragraph", Arrays.asList(text), attributes, new HashMap<Object, Object>());
    }
}
```

**Comment by vicmosin** [comment]
Sorry, it was the spring-restdocs issue.

**Comment by mojavelinux** [comment]
>  I tried to build it with a Java extension but it seems I cannot register it to the source block, it just won't trigger for it.

You can't register a block processor for a built-in block. (That's because the idea is to parse blocks that the built-in parser does not know how to parse). If you want to manipulate the content of a built-in block, then you'd use a Treeprocessor.

**Comment by mojavelinux** [comment]
This could also be a tabs vs spaces issue. We plan to address this in core. See https://github.com/asciidoctor/asciidoctor/issues/1170.

**Comment by vicmosin** [comment]
As I said it was internal issue and I found how to solve it. If anybody wants to check - take a look at `spring.jackson.serialization.indent_output` flag and appropriate source codes. It works perfectly

**Comment by abelsromero** [comment]
Thanks for the info :smile: Nice to know is completely fixed.
