### ISSUE TITLE
Warning for broken internal cross-references

### ISSUE THREAD

**Issue by Svish** [asciidoctor/asciidoctor-maven-plugin#175]
Is there a way to enable warnings for broken cross references? Like I get if I try to include a file that doesn't exist, it would be nice with some warnings when I build if there's a cross reference that goes to nowhere.

**Comment by mojavelinux** [comment]
It's not the job of the converter to validate cross references as that would require network access and drastically slow down the converter. However, I do support the idea of having a validate tool (or even phase) that would do this. One tool to use in the interim is html-proofer which works through a document to find broken links.

**Comment by Svish** [comment]
Was mainly thinking cross-references within the same document, so no network should be necessary then? I don't really know how any of this works, but to me it seems that it should be possible as broken cross-references seems to look different. They seem to get wrapped in square brackets. So to me it seems like there should be some sort of step in the process where it should be possible to throw out a warning of "hey, you should check out this broken cross-reference I just tried to process".

**Comment by mojavelinux** [comment]
In that case, a warning on an internal cross reference is very reasonable. What we'll want to do is issue that warning and then hook it into the messages once we implement https://github.com/asciidoctor/asciidoctor/issues/44.

Could you file an issue in core to issue a warning when an internal cross reference is not found? https://github.com/asciidoctor/asciidoctor Once we implement all these parts, it will just work in the Maven plugin.

**Comment by Svish** [comment]
Done @ asciidoctor/asciidoctor#1586 :+1:

**Comment by mojavelinux** [comment]
Thanks!

**Comment by mojavelinux** [comment]
Let's close this since we now have the issue in core.
