### ISSUE TITLE
Render asciidoc filename via document.html.erb?

### ISSUE THREAD

**Issue by Jotschi** [asciidoctor/asciidoctor-maven-plugin#176]
Is it somehow possible to render the source asciidoc filename when using a ```document.html.erb``` template?

I tried various attributes from this list but i was unable to find the correct one.

https://github.com/asciidoctor/asciidoctor/wiki/Catalog-of-Document-Attributes

**Comment by mojavelinux** [comment]
As long as the safe mode is set to safe or unsafe, you can use `attr :docfile`.

**Comment by mojavelinux** [comment]
You can see where these are assigned here: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L1324

**Comment by mojavelinux** [comment]
The Maven examples shows these attributes in action: https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoc-to-html-example

**Comment by mojavelinux** [comment]
Please reopen if the explanation is not clear.
