### ISSUE TITLE
baseDir should be set when Asciidoctor is invoked from the Maven Site plugin

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-maven-plugin#180]
The baseDir option should be set when Asciidoctor is invoked from the Maven Site plugin. Currently, the baseDir is defaulting to the root of the project. This means that top-level includes have to be specified using a relative path from the project root instead of relative to the main file.

The behavior that needs to be emulated is specified here: https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L213-L222

There's currently no way to provide options to the Maven Site plugin, so it should use the fallback behavior.

**Comment by mstanleyjones** [comment]
Also, if you are trying to use maven-site with Asciidoc, but also to build a PDF payload, the include:: syntax for making the HTML works breaks the PDF.

**Comment by mojavelinux** [comment]
Technically, there is a way to work around this problem, but I'm only mentioning it for completeness, not because it's elegant.

You can simple define an attribute as the root of the includes in the document header per backend.

```
ifdef::backend-pdf[]
:includedir: src/site/asciidoc
endif::[]
ifndef::backend-pdf[]
:includedir: .
endif::[]

include::{includedir}/part.adoc[]
```

Again, we really don't want to have to resort to this, but in the meantime it might help to get you by.

**Comment by mojavelinux** [comment]
Btw, we should have an attribute set in the Maven Site configuration that indicates that we're in the maven site environment. That would make conditionals like this more clear. Something like `env-maven-site`.

**Comment by mojavelinux** [comment]
Once I figured out how to inject the MavenProject into the class, I was able to access the basedir of the project and from there the path to the AsciiDoc files in the site. The basedir will be set to the following path by default:

* ${project.basedir}/src/site/asciidoc

This value can be configured using a configuration property under the site configuration.

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-site-plugin</artifactId>
    <version>3.3</version> <!-- 3.4 also works -->
    <configuration>
        <asciidoc>
            <baseDir>${project.basedir}</baseDir>
        </asciidoc>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctor-maven-plugin</artifactId>
            <version>1.5.3</version>
        </dependency>
    </dependencies>
</plugin>
```
