### ISSUE TITLE
Set 'html5' as default backend

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#188]
Current  [code](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L88) and README states that the default backend is `docbook`.
To avoid confusions adn to align it with what Asciidoctor uses (http://asciidoctor.org/docs/user-manual/#selecting-an-output-format), maybe we should change it to `html5`.

**Comment by mojavelinux** [comment]
I'd be fine with that, but probably for 1.6.0.

The default docbook was chosen at the time when the primary goal of the
plugin was to connect it to the DocBook toolchain, but we've graduated from
there :)
