### ISSUE TITLE
Document use of '_' to hide documents and directories

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#190]
As discussed in http://discuss.asciidoctor.org/Suppress-quot-Section-title-out-of-order-quot-warnings-td4157.html, it is needed to document the use of the `_` as prefix to hide AsciiDoc files and folders, see:
- https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/AsciiDocDirectoryWalker.java#L17
- https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L273-L275

**Comment by mojavelinux** [comment]
:+1: 

I think it's also important to explain why we have this feature. The use case in the linked thread is the best example I think.

**Comment by abelsromero** [comment]
I'm seeing that this filter is only applied when rendering. This means that folders and other files (images, css) with '_' are copied to the output directory.
I think we should keep this consistent.

**Comment by abelsromero** [comment]
By consistent, I mean, applying the same filter when copying resources.

**Comment by mojavelinux** [comment]
:+1:

**Comment by abelsromero** [comment]
Just tested with current v2.0.0 and anything (dir, resource file or source file) are no copied.
