### ISSUE TITLE
Integration tests fail with Maven 3.3.+ on Windows

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#194]
Since Maven 3.3.0 the command `mvn.bat` has been renamed to `mvn.cmd`.
This causes the `maven-invoker-plugin` (v1.8) to fail on Windows because it looks for a .bat file.

Newer version 2.0.0 supposedly fixes this issue ([MNG-5792](https://issues.apache.org/jira/browse/MNG-5792)) but test fail the same with no error message. Further investigation is required to find the cause.
Until this is fixed, the project will be stuck with using Maven 3.2.+ for the Appveyor tests.

Right now, the workarround for local environments is to copy & rename `mvn.bat` to `mvn.cmd` inside the Maven installation folder.

**Comment by mojavelinux** [comment]
Why would they do this?

Maybe we could use that workaround in the integration test environment too. That would enable us to move forward.

**Comment by abelsromero** [comment]
I just created the issue to ensure I did not forget this or in case someone else wanted to look into it.
Truth is after https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/193 I want to check all versions because some are really old. For instance we are still using Maven API 2.2.1.

**Comment by mojavelinux** [comment]
:+1:

**Comment by abelsromero** [comment]
Run some test and found out that it was an issue with the execution rights of the maven command when using Sdkman (https://github.com/sdkman/sdkman-cli/issues/404) on Windows. Sdkman + MacOS works fine.
To be 100% sure, I created a branch in my repo with maven 3.3.3 and the new invoker plugin 2.0.0 and it works on Appveyour too.

I'll do the final PR later next week.

**Comment by mojavelinux** [comment]
Excellent! Nice job on the investigative work.

**Comment by abelsromero** [comment]
PR sent https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/195
