### ISSUE TITLE
Generated diagram images failed to be embedded in pdf

### ISSUE THREAD

**Issue by jinahya** [asciidoctor/asciidoctor-maven-plugin#196]
I'm generating diagrams. Images generated in `target/generated-docs-images`.
HTML successfully renders those generated images, but pdf fails.

```
asciidoctor: WARNING: image to embed not found or not readable: \
/path/to/src/main/asciidoc/images/diag-0eecdb8aae25da40f6cf41c33fce8cb1.png
```

I'm using following dependencies.

``` xml
        <dependencies>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>1.5.4</version>
            <!--<version>1.6.0-alpha.1</version>-->
          </dependency>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-diagram</artifactId>
            <version>1.3.1</version>
          </dependency>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>1.5.0-alpha.11</version>
          </dependency>
          <!--          <dependency>
            <groupId>org.jruby</groupId>
            <artifactId>jruby-complete</artifactId>
            <version>9.0.4.0</version>
          </dependency>-->
        </dependencies>
```

**Comment by mojavelinux** [comment]
When using Asciidoctor Diagram with the PDF converter, it's necessary to set the imagesdir to the output directory. That also means that you need to copy all the images there before the converter runs so it can find them all in one place.

This is a common problem when using Asciidoctor Diagram when the input and output directories are different (which is the case with any build tool). We really need to document this scenario clearly, but also find some way to make it simpler. It's a software design challenge.

**Comment by mojavelinux** [comment]
The software design challenge is how to work with both input images and generated image across different folders referenced in different parts of the document. Right now, the only practical solution is to ensure all the images end up in one place before the converter runs.

**Comment by abelsromero** [comment]
> We really need to document this scenario clearly

A part from adding some not in AsciidoctorJ manual, we can improve the current [example](https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-diagram-example). Right now the examples is pretty simple.

**Comment by jinahya** [comment]
I understand that problem is not simple.

With some curiosities, I tested.

* I put a static image on `src/main/asciidoc/images`
  * the static image copied to `target/generated-docs/images`
  * diagrams generated in `target/generated-docs/image`
  * asciidoc complains : `image ...: .../src/main/asciidoc/images/diag...png`
* I set `<imagesDir>../../../target/generated-docs/images</imagesDir>`
  * the static image copied into `target/generated-docs/images`
  * diagrams **not** generated in `target/generated-docs/images`, I don't know where.
  * asciidoc complains: `image...: .../target/generated-docs/images/diag....png`

Does this give you any clue? The `-X` option show me nothing practical.

Thanks.

**Comment by mojavelinux** [comment]
> I set <imagesDir>../../../target/generated-docs/images</imagesDir>

You should use an absolute path when configuring the PDF converter. Obviously, this attribute would be to be different than the value for the HTML converter.

> diagrams not generated in target/generated-docs/images, I don't know where.

When you set the imagesdir, you also have to set the imagesoutdir (used by Asciidoctor Diagram). Even I forget the exact relationship between the two, but I know enough to know that there are two attributes.

**Comment by jinahya** [comment]
Report.
With following attributes
```xml
            <imagesdir>${project.build.directory}/generated-docs/images</imagesdir>
            <imagesoutdir>${project.build.directory}/generated-docs/images</imagesoutdir>
```
pdf renders diagram images but not for static images.
html renders both static and generated.

**Comment by mojavelinux** [comment]
I think the problem is that the plugin copies the images after conversion.
It needs to copy them first. That needs to be confirmed.

**Comment by abelsromero** [comment]
> It needs to copy them first. That needs to be confirmed.
I can confirm it.
If images need to be copied first, right now the option I see is to use the maven-resources-plugin in a previous phase to copy them, e.g., initialize.

However, if my memory serves, I recall doing some testing with images and PDF and it worked. Also it comes to my mind a related issue in asciidoctor-pdf that got fixed.
I cannot look into it today, but I'll have some time tomorrow afternoon (me GMT+1). If I confirm it, then we can copy resources first, I cannot think a reason not to do so.

**Comment by mojavelinux** [comment]
It's not a problem strictly with images in PDFs but rather when images are sourced from different locations (static vs generated by Asciidoctor Diagram). The image must be there at the time the converter runs because it has to read the image and stick it into the file. In HTML, it doesn't care when the image shows up, as long as it is there when viewed.

**Comment by mojavelinux** [comment]
I can now confirm that the copying of assets happens after the converter runs. However, it needs to happen first for use cases like this one. So this is definitely a change that should happen in the plugin. We could even have a plugin option that controls when the copy happens (if we find that control necessary).

**Comment by dashorst** [comment]
Add this to your POM:

```xml
        <plugin>
          <!-- deze plugin is toegevoegd om de images te kopiëren voordat de adoc generator
               aan het werk gaat. Die kan anders de images niet vinden, en weigert in twee
               folders te kijken. -->
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>2.7</version>
          <executions>
            <execution>
              <id>copy-resources</id>
              <phase>initialize</phase>
              <goals>
                <goal>copy-resources</goal>
              </goals>
              <configuration>
                <outputDirectory>${project.build.directory}/generated-docs/images</outputDirectory>
                <resources>          
                  <resource>
                    <directory>src/main/asciidoc/images</directory>
                    <filtering>false</filtering>
                  </resource>
                </resources>
              </configuration>
            </execution>
          </executions>
        </plugin>
```
This will bind the Maven Resources Plugin to the `initialize` phase of the build and triggers it to run before the PDF generator.

**Comment by smil2k** [comment]
Hi,

The following configuration works as expected:. 

`<build>
    <plugins>
      <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>1.5.5</version>
        <dependencies>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-diagram</artifactId>
            <version>1.5.4</version>
          </dependency>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>1.5.0-alpha.16</version>
          </dependency>
        </dependencies>
        <configuration>
          <sourceDirectory>src/main/resources</sourceDirectory>
        </configuration>
        <executions>
          <execution>
            <id>generate-pdf-doc</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>process-asciidoc</goal>
            </goals>
            <configuration>
              <backend>pdf</backend>
              <sourceHighlighter>coderay</sourceHighlighter>
              <requires>
                <require>asciidoctor-diagram</require>
                <require>coderay</require>
              </requires>
              <attributes>
                <imagesdir>${project.build.directory}/generated-docs/images</imagesdir>
                <imagesoutdir>${project.build.directory}/generated-docs/images</imagesoutdir>
                <icons>font</icons>
                <pagenums/>
                <toc/>
                <idprefix/>
                <idseparator>-</idseparator>
              </attributes>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>`

**Comment by abelsromero** [comment]
yes, @smil2k it works! Thanks for the note.
I tests with last versions and it works fine.
* AsciidoctorJ: 1.5.7
* Asciidoctorj-diagram: 1.5.9
* Asciidoctorj-pdf: 1.5.0-alpha.16
* JRuby: 9.1.17.0 (got problems with 9.2.0.0)

Resources are now copied before rendering since v 1.5.5 of the plugin, so this issue can be closed.
