### ISSUE TITLE
A Table of Contents header is added on table cells with an AsciiDoc style component

### ISSUE THREAD

**Issue by ntfc** [asciidoctor/asciidoctor-maven-plugin#199]
Hi,

I have a problem when using the AsciiDoc cell style component (`a|`) with the maven plugin.
It is somehow related to the table of contents and the existance of an `index.html` (generated with
the `asciidoctor` command) on the same directory as of `index.adoc`. It only happens when the `toc` is enabled, either with `auto`, `left` or `right`.

I could only reproduced it with asciidoctor-maven-plugin **1.5.3** 

What happens is that a `Table of Contents` header is introduced on every table cell that contains `a|`, making them look like the following:

![wrong](https://cloud.githubusercontent.com/assets/651413/12660436/adfa08e6-c60b-11e5-92cb-8ec942175a70.png)

The stranger thing is that if I generate the `index.html` with `asciidoctor`, and then execute `mvn clean package` again, I get the correct output:

![ok](https://cloud.githubusercontent.com/assets/651413/12660458/c3fa86b6-c60b-11e5-923c-53265e736e0f.png)

Here are the gists of [pom.xml](https://gist.github.com/ntfc/b66364a0439b356835da) and [index.adoc](https://gist.github.com/ntfc/16ebf7f85a6946a8c13b).

The steps to reproduce the issue are:
1. `mvn clean package`: Wrong output on `target/generated-docs/index.html`
2. `asciidoctor index.adoc`: Correct output on `src/main/asciidoc/index.html`
3. `mvn clean package`: Correct output on `target/generated-docs/index.html`
4. `rm src/main/asciidoc/index.html && mvn clean package`: Wrong output on `target/generated-docs/index.html`

**Comment by mojavelinux** [comment]
This is a known bug in Asciidoctor 1.5.3 and is fixed by migrating to Asciidoctor 1.5.4. Until an update of the Maven plugin is available, you need to manually specify the version of AsciidoctorJ. See https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-html-example/pom.xml#L33-L37

**Comment by ntfc** [comment]
Thank you @mojavelinux, that solves it for me!
