### ISSUE TITLE
Parameters should be consistent with attributes names

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-maven-plugin#200]
With Maven we can configure a plugin from the command-line:

```
mvn asciidoctor:process-asciidoc -Dasciidoctor.sourceDir=src/docs/asciidoc
```

First, I think we should add an example somewhere in the documentation:

> The command line `mvn asciidoctor:process-asciidoc -Dasciidoctor.sourceDir=src/docs/asciidoc` is equivalent to the configuration below:

 ```
<plugin>
    <configuration>
        <sourceDirectory>src/docs/asciidoc</sourceDirectory>
    </configuration>
</plugin>
 ```

Most of the time parameters names and attributes names are the same but `sourceDirectory` parameter is named `sourceDir` and `outputDirectory` is named `outputDir`.

To be consistent we should use the same name and decide to go `directory` everywhere or `dir` everywhere.

**Comment by abelsromero** [comment]
> To be consistent we should use the same name and decide to go directory everywhere or dir everywhere.

I think the most obvious option is to go `directory`. To me it makes more sense to align properties with the XML labels than the other way arround.

@Mogztter btw, did you test if attributes can be set? I saw your tweet yesterday about it. I don't think it can be done since attributes is a Map.

**Comment by Mogztter** [comment]
> I think the most obvious option is to go directory. To me it makes more sense to align properties with the XML labels than the other way arround.

That's fine for me.

> @Mogztter btw, did you test if attributes can be set? I saw your tweet yesterday about it. I don't think it can be done since attributes is a Map.

Yes but didn't succeed.
I think we could create another parameter with a `String` type (or maybe a `List` type).


```
mvn asciidoctor:process-asciidoc -Dasciidoctor.attributesMap="stylesheet=my-theme.css toc"
```

The following command will fill the `attributes` parameter:

```java
attributes.put("stylesheet", "my-theme.css");
attributes.put("toc", true);
```

But this is for another issue :smile: 

Btw the plugin is really great! I use it everyday :+1:

**Comment by mojavelinux** [comment]
I recommend just `-Dasciidoctor.attributes`. The fact that the value is a string is recognizable in the Asciidoctor ecosystem, so I think it fits. It's also the most reasonable way to assign it on the commandline. You may have to do some type checking internally, but this would be ideal if it works.

**Comment by abelsromero** [comment]
> But this is for another issue.

Please, feel free to file an issue. 

> Btw the plugin is really great!

That's the merit of all people involved. Imho, there's still lots of improvements to do, issues like this prove that some featues are not well tested/documented.

**Comment by Mogztter** [comment]
Thanks!
Le 7 févr. 2016 8:09 AM, "Abel Salgado Romero" <notifications@github.com> a
écrit :
