### ISSUE TITLE
Add maven wrapper

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#204]
Should we add the maven-wrapper?
## PROS :+1:
- ...well, all the same as gradle wrapper: easy to set up environment, ensure the version of maven, etc.
- jruby uses it 
- Will ensure smae maven version for TravisCI and Appveyor.
  · TravisCI uses default maven installed, version 3.2.5. Note that we cannot modify it unless we install another one and replace path variables.
  · Appveyor uses maven installed from our own script (we have 100% control). Current version 3.3.9
## CONS :-1:

· May surprise some maven users
· May require some manteinance from time to time.

**My vote is including it.**

**Comment by mojavelinux** [comment]
For the build of the plugin itself, definitely. It will make things more consistent. Of course, you can still run the build without the wrapper, but it's there for us to run in CI.

**Comment by LightGuard** [comment]
:+1:

On Tuesday, February 9, 2016, Dan Allen <notifications@github.com> wrote:

> For the build of the plugin itself, definitely. It will make things more
> consistent. Of course, you can still run the build without the wrapper, but
> it's there for us to run in CI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/204#issuecomment-182041615>
> .
>


-- 
Sent from Gmail Mobile

**Comment by abelsromero** [comment]
Maven Wrapper does not support Java 6, so the build in TravisCI fails.
Maybe we should schedule this for asciidoctor 1.6.0 and remove compatibility with Java 6 then.

**Comment by LightGuard** [comment]
That's the pits. I'm sure there are a bunch of people still using Java 6 :(

On Tue, Feb 9, 2016 at 3:18 PM, Abel Salgado Romero <
notifications@github.com> wrote:

> Maven Wrapper does not support Java 6, so the build in TravisCI fails.
> Maybe we should schedule this for asciidoctor 1.6.0 and remove
> compatibility with Java 6 then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/204#issuecomment-182104125>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by leif81** [comment]
> That's the pits. I'm sure there are a bunch of people still using Java 6 :(

Maybe, but I hope not!
Java 6 was EOL'd in 2013. Even Java 7 was in 2015.

**Comment by mojavelinux** [comment]
Regardless, this is a decision each project has to make (as it's a support issue and cost). There will always be people lingering, but we can't enable them. Support for Java 6 is over once we switch to 1.6.0. We're making that call.

**Comment by abelsromero** [comment]
Even if 1.6.0 is close, I'll try to get something. Even if it just for fun I'd like to see what can be done with TravisCI.

**Comment by abelsromero** [comment]
Too much effort just to get TravisCI to use the default maven installation when using `openjdk6`.
Just setting this to be fixed with 1.6.0

**Comment by abelsromero** [comment]
Maven wrapper has been adopted as official maven component. I guess we can wait a bit more to see how is the official version.
