### ISSUE TITLE
Adding support to define attribues using command line arguments

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#206]
As mentioned in https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/200 by @Mogztter, it would would be nice to be able to pass asciidoctor attributes using command line arguments like

````
mvn asciidoctor:process-asciidoc -Dasciidoctor.attributes="stylesheet=my-theme.css toc"
```

It is easy to implement, it only requires adding a new attribute and some maven anotations.

I have a working version https://github.com/abelsromero/asciidoctor-maven-plugin/blob/attributes_command/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L88-L89, and it works perfectly on all OS (Win, Lin, Mac). However, there is an open issue with the tests (https://issues.apache.org/jira/browse/MINVOKER-198).
To make things clear, only test fail, if I install the plugin in my local repo and use it, attributes can be passes as requested.

So, wdyt? Should we add it without an it-test for now?

**Comment by mojavelinux** [comment]
I like it!

My only request is that we simplify the name. I'm not a fan of "attributesMap". First, it's not a map, so that's confusing. Second, it's too long. If we can get "attributes" to work (using some Maven trickery), then perhaps we can just make it "attrs" or "attrlist". wdyt?

**Comment by abelsromero** [comment]
Sure, the current implementation ustes attributes in fact.
I updated the issue description to make it clear.

**Comment by mojavelinux** [comment]
Super!!

**Comment by Mogztter** [comment]
This is great! Thanks @abelsromero, I will give it a try :+1:
