### ISSUE TITLE
How to add includes using the IncludeProcessor?

### ISSUE THREAD

**Issue by Systemdir** [asciidoctor/asciidoctor-maven-plugin#210]
I have the problem, asciidoc is not parsing new includes added using the IncludeProcessor. 
My goal is to write an extension including multiple asciidoc files in a certain order from a directory. The included files look fine but all includes in them don't work.

**Example:**
Following code: 

```
@Override
public boolean handles(String target) {
    return target.startsWith("adocs");
}

@Override
public void process(DocumentRuby document, 
     PreprocessorReader reader, String target, Map<String, Object> attributes) {
        reader.push_include("include::{asciidoc-files}\\01-first.asciidoc[]",
                                                target,target,1,attributes);
}
```

with following asciidoc:

```
= Documentation
:asciidoc-files: ..\asciidoc

// include asciidoc files here
include::adocs[]
```

results in:

```
Documentation

include::..\asciidoc\01-first.asciidoc[]
```

**Comment by Systemdir** [comment]
I tried the same with the Preprocessor getting the same problem.

```
public class MergeAsciidoc extends Preprocessor {
    public MergeAsciidoc(Map<String, Object> config) {
        super(config);
    }
    
    public PreprocessorReader process(Document document, PreprocessorReader reader) {
        final List<String> lines = reader.readLines();

        StringBuilder stringBuilder = new StringBuilder();

        for(String line:lines){
            if(line.startsWith("#include:")){
                String path = line.substring("#include:".length()).trim();
                stringBuilder.append(addAsciidocFiles(new File(path)));
            }else {
                stringBuilder.append(line);
            }
            stringBuilder.append("\n");
        }

        //todo: is document.getAttributes() correct?
        reader.push_include(stringBuilder.toString(), "", "", 1, document.getAttributes());

        return reader;
    }
   
    ...
}
```

**Comment by abelsromero** [comment]
I see many things that could be going wrong.
So to narrow it a bit, I am going to ask for some more info.
First, could you check that the  extension is being executed? Maybe adding some log/println or just debugging.
Then, to discard any configuration problem, how is the extention being configured? The maven plugin offers two ways to setup extensions: SPI or though pom configuration. Which one are you using?

**Comment by Systemdir** [comment]
Thanks for the fast reply. 

To your questions: 
First - the extensions are executed (tested with breakpoint and println). As can also be seen from my first post, the extension is executed and does the text replacement. The problem is, that the added include is not being evaluated.

Second - I configured the extension via maven pom

Here a snippet out of my pom:
```
    ...

<execution>
	<id>output-html</id>
	<phase>generate-resources</phase>
	<goals>
		<goal>process-asciidoc</goal>
	</goals>
	<configuration>
		<sourceHighlighter>coderay</sourceHighlighter>
		<backend>html5</backend>
		<attributes>
			<imagesdir>./images</imagesdir>
			<toc>left</toc>
			<icons>font</icons>
			<sectanchors>true</sectanchors>
			<idprefix/>
			<idseparator>-</idseparator>
			<docinfo1>true</docinfo1>

			<!-- thought maybe this might help. It didn't -->
			<safe-mode>UNSAFE</safe-mode>
			<allow-uri-read>true</allow-uri-read>
		</attributes>

		<extensions>
			<extension> <!-- InlineMacroProcessor - doing different stuff that works fine -->
				<className>extensions.Classpathcheck</className>
				<blockName>class</blockName>
			</extension>
			<extension> <!-- this is the extension in question -->
				<className>extensions.MergeAsciidoc</className>
			</extension>
		</extensions>
	</configuration>
</execution>

     ...
```

**Comment by abelsromero** [comment]
Initially I don't see anything wrong, but I'm not sure how push_include behaves in a preprocessor. Copying the expert here cc @robertpanzer

**Comment by mojavelinux** [comment]
> //todo: is document.getAttributes() correct?

No, you should be passing along the attributes on the original include directive, if you need them.

**Comment by mojavelinux** [comment]
I tried this with a Ruby extension and it worked. I wonder if the delegation in AsciidoctorJ is causing the PreprocessorReader to not act like a preprocessor (instead just a regular reader).

**Comment by mojavelinux** [comment]
You can test that theory by putting and `ifdef` line in the source you push onto the reader and see if it gets unprocessed. If the `ifdef` doesn't get processed, then we know subsequent includes won't either.

**Comment by mojavelinux** [comment]
In a quick test with AsciidoctorJ, but assumption seems to hold. The PreprocessorReader being manipulated is not acting like a Preprocessor. Very likely AsciidoctorJ would fail such a test. Therefore, this should be opened in AsciidoctorJ.

Until then, you'll have to push preprocessed lines onto the reader (in other words, you have to do the preprocessing yourself).

**Comment by Systemdir** [comment]
Thank you for your help. I added an `ifdef ` directive to the sources pushed onto the reader and it is indeed unprocessed.

I'll open an issue in the AsciidoctorJ project.

**Comment by abelsromero** [comment]
I'll close this as the issur is already registered in Asciidoctorj.
