### ISSUE TITLE
Nested non-text elements in list items result in the list item not being recognized

### ISSUE THREAD

**Issue by mrietveld** [asciidoctor/asciidoctor-maven-plugin#219]
In the following list, the second list item is not recognized: 

```
* first element
*
+
[NOTE]
====
Note in second element
====
+
Second element text
```

However, it's possible to 'hack' around this by doing this: 

```
* first element
* $$$$
+
[NOTE]
====
Note in second element
====
+
Second element text
```

**Comment by mojavelinux** [comment]
In AsciiDoc, a list item must have text. You can workaround this by using an attribute reference (which counts as text) that resolves to empty:

```
* first element
* {empty}
+
[NOTE]
====
Note in second element
====
```

Unfortunately, there's no way at the moment to avoid the empty `<p></p>` in the output. You'll need to use CSS to get the styling behavior you want.

This might make a good FAQ. wdyt? http://asciidoctor.org/docs/faq/

**Comment by mojavelinux** [comment]
> Unfortunately, there's no way at the moment to avoid the empty <p></p> in the output. 

We could check to see if the value is empty and skip adding the `<p></p>`. Please file an issue in core if you are interested in seeing this happen.

**Comment by mrietveld** [comment]
@mojavelinux Ahh, It's good to know about the {empty} attributes. As far as I'm concerned, there's no reason yet for me to file an issue in core. 

(FYI: this was actually related to docbookrx tests/use, of course. :) )
