### ISSUE TITLE
Impossible to create formatted text that starts with 2 . or *

### ISSUE THREAD

**Issue by mrietveld** [asciidoctor/asciidoctor-maven-plugin#220]
So none of the following cases allow us to add the literal text:

> ** text starting with **stars**

* List items:
 
```
** text starting with *stars*
.. text starting with *dots*
```
gives us list items. 

* Escaped stars:

```
\** text starting with *stars*
\.. text starting with *dots*
```
gives us the literal text: 

> \\** text starting with **stars**
> \\.. text starting with **dots**

* Escaped using double $ signs:

```
$$** text starting with *stars*$$
$$.. text starting with *dots*$$
```

gives us

> ** text starting with \*stars*
> .. text starting with \*dots*

* And I don't know of any other ways/hacks to get this..

**Comment by mrietveld** [comment]
Oh, nevermind: 

`$$**$$ text starting with *stars*`

Apologies!

**Comment by abelsromero** [comment]
No worries :)

**Comment by mojavelinux** [comment]
The plus passthrough is preferred in Asciidoctor:

```
+**+ text starting with *stars*.
```

Anther approach is to use attributes:

```
{asterisk}{asterisk} text starting with *stars*
```

Backslashes in AsciiDoc Python and Asciidoctor are not "inception friendly" yet. See https://github.com/asciidoctor/asciidoctor/issues/901
