### ISSUE TITLE
How to force asciidoctor-maven-plugin desired version of this or that ruby gem?

### ISSUE THREAD

**Issue by AlexanderZobkov** [asciidoctor/asciidoctor-maven-plugin#221]
Hello,
I'm trying to enable the latest version of prawn-svg in Maven build by using the same trick as applied for prawn in asciidoctor-pdf-with-theme-example/pom.xml. Unfortunatly, it seems the trick does not work for prawn-svg. 
It's reproducible with asciidoctor-pdf-with-theme-example and svg files attached to https://github.com/mogest/prawn-svg/issues/49. 

Could you please suggest how to force asciidoctor-maven-plugin to use desired version of prawn-svg?  
Or troubleshoot ruby class loading mechanism?

**Comment by AlexanderZobkov** [comment]
Finally, I was able to enforce the latest version of prawn-svg. Here are the steps based on asciidoctor-pdf-with-theme-example:
1) Add dependency on rubygems:prawn-svg:0.25.1
2) Unpack org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.10.1:jar to ${project.build.directory}/gems-provided directory
3) Patch ${project.build.directory}/gems-provided/specifications/asciidoctor-pdf-1.5.0.alpha.10.gemspec to allow to use prawn-svg  versions above 0.21.0 
--  `dependency(%q<prawn-svg>, ["= 0.21.0"])` is replaced with `dependency(%q<prawn-svg>, ["> 0.21.0"])`
4) Remove dependency on asciidoctorj-pdf for asciidoctor-maven-plugin.

**Comment by AlexanderZobkov** [comment]
@mojavelinux, In  asciidoctor-pdf-1.5.0.alpha.10.gemspec, for some portion of dependencies exact versions are defined but for another portion of dependencies range versions are defined.
 s.add_runtime_dependency(%q<prawn>, ["< 3.0.0", ">= 1.3.0"])
 s.add_runtime_dependency(%q<prawn-svg>, ["= 0.21.0"]) <- Does not allow to use the latest version even if it's provided in gem path/load path.
 s.add_runtime_dependency(%q<prawn-icon>, ["= 1.0.0"])

For dependencies that declared with exact versions, I propose to specify with version ranges (or no version at all). 
It would allow, in Maven builds, to have a flexibility to upgrade ruby gems without a need to wait to next version of org.asciidoctor:asciidoctorj-pdf maven artifact.

wdyt?

**Comment by mojavelinux** [comment]
Unfortunately, we have to be specific about the versions of things used in order for Asciidoctor PDF to work properly across all the environments we support.

**Comment by mojavelinux** [comment]
> It would allow, in Maven builds, to have a flexibility to upgrade ruby gems without a need to wait to next version of org.asciidoctor:asciidoctorj-pdf maven artifact.

I'm pretty sure that the Maven build can already do this. It's probably tedious, but it is possible.

**Comment by AlexanderZobkov** [comment]
As I mentioned above, I was able to enforce required for me version of prawn-svg in asciidoctor-pdf-1.5.0.alpha.10 gem.By hacking the gemspec file for asciidoctor-pdf gem during the maven build. It seems JRuby takes into account information in gems specs when try to load required libraries.

is it possible to instruct the gemspec to work in the following way?:
It's required to use specific version(s) of this or that dependency but if you are not able to find gem of required version(s), print a warning and try to use the latest found version.

**Comment by mojavelinux** [comment]
Yes, there is. It is possible to declare gems without dependencies. Of course, you then have to declare every gem you want to use. I believe there is an example of this in the maven-examples project. 

https://github.com/asciidoctor/asciidoctor-maven-examples/issues/41#issuecomment-171944436

**Comment by AlexanderZobkov** [comment]
Thanks Dan! 

Can we relax  a bit versions for asciidoctor-pdf dependencies by using "~>" operator?

Extraction from asciidoctor-pdf gem spec (HEAD. master branch):

  s.add_development_dependency 'rake', '~> 10.0' 
  #s.add_development_dependency 'rdoc', '~> 4.1.0'

  s.add_runtime_dependency 'asciidoctor', '~> 1.5.0'
  # Prawn 2.x requires Ruby 2.x, so cast a wider net
  s.add_runtime_dependency 'prawn', '>= 1.3.0', '< 3.0.0'
  s.add_runtime_dependency 'prawn-table', '0.2.2'  **<- For this dependency**
  s.add_runtime_dependency 'prawn-templates', '0.0.3' **<- For this dependency**
  s.add_runtime_dependency 'prawn-svg', '0.25.1' **<- For this dependency**
  s.add_runtime_dependency 'prawn-icon', '1.1.0' **<- For this dependency**
  s.add_runtime_dependency 'safe_yaml', '~> 1.0.4'
  s.add_runtime_dependency 'thread_safe', '~> 0.3.5'
  # For our usage, treetop 1.6.2 is slower than 1.5.3
  s.add_runtime_dependency 'treetop', '1.5.3' **<- For this dependency**

**Comment by mojavelinux** [comment]
Unfortunately, we can't. Asciidoctor PDF works with a very specific set of dependencies due to the fact that Prawn moves around a lot. It's important, esp during the alpha cycle, to lock the dependencies so that we can focus on the Asciidoctor PDF code and not on integration problems.

Once the Prawn ecosystem and Asciidoctor PDF stabilize a bit, and we have a test suite, then we can look at loosening the dependencies.

**Comment by AlexanderZobkov** [comment]
Alright, thanks.
