### ISSUE TITLE
Invalid table cell content when generated with asciidoc code within it and a TOC

### ISSUE THREAD

**Issue by jaubin** [asciidoctor/asciidoctor-maven-plugin#224]
Hi,

I've found a rather strange bug in ASCIIDoctor Maven Plugin. It does not affect the standard asciidoctor command.

DO : create a file with a toc, and with a toc title, as follows : 

:source-highlighter: coderay
:coderay-css: style

= Documentation
:toc:
:toc-title: Index

DO : inside this table create a table with a content as follows : 

[cols="1,3a,2", options="header"]
|===
| Name
| Description
| Execution date

| foobar

|
|
- did blablabla
- did helloworld

| 16/08/16 11:36

| foo2

|
|
- Hello
- World

| 17/08/11 12:45

|===

DO : generate the document with asciidoctor
EXPECT : everything goes fine.
DO : generate the document with the asciidoctor maven plugin.
EXPECT : same result as with command asciidoctor
ACTUAL : the title of the TOC is put in every cell of the "Description" column.

NOTE : if you remove the "a" in the column description everything generates without the TOC title...

**Comment by mojavelinux** [comment]
This was a known issue with Asciidoctor 1.5.3. You need to use Asciidoctor 1.5.4. Since the plugin still uses 1.5.3 by default, that means you have to specify the version of AsciidoctorJ explicitly.

**Comment by duffy356** [comment]
Updating Asciidoctor to 1.5.5 has solved the problem for me.

**Comment by abelsromero** [comment]
Thanks for heads up!
