### ISSUE TITLE
No source code highlighting

### ISSUE THREAD

**Issue by DanielSWolf** [asciidoctor/asciidoctor-maven-plugin#228]
I have an AsciiDoc file that contains some source code; also, its header contains the line `:source-highlighter: highlight.js`.

When I generate HTML via `asciidoctor document.adoc`, the resulting HTML file correctly highlights the source code.

However, when I generate HTML for the same file via the maven plugin, the source code has no highlighting at all. I tried adding the configuration attribute `<source-highlighter>highlight.js</source-highlighter>` in `pom.xml` (just because the Readme told me to), but it didn't make any difference.

The difference between the generated files is that the AsciiDoctor build contains the following lines, which enable syntax highlighting; the Maven build does not.

```xml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/styles/github.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js"></script>
<script>hljs.initHighlighting()</script>
```

How can I instruct the Maven plugin to include these lines the way AsciiDoctor does?

**Comment by abelsromero** [comment]
For the recommended way to integrate source highlinging is using the `<sourceHighlighter>` option.

Here is an example:
https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-html-example/pom.xml#L61

**Comment by abelsromero** [comment]
Btw, I just tried setting the attribute in the `<attributes>` and it worked also.
Basically, most of the [options ](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/README.adoc#configuration-options) available are shortcuts to make common configurations easier, but under-the-hood, they just format the attributes.

This should also work
```
  <configuration>
    <backend>html5</backend>
    <attributes>
        <source-highlighter>highlight.js</source-highlighter>
    </attributes>
  </configuration>
```

**Comment by mojavelinux** [comment]
Correct. The option (which is just an shorthand for setting the attribute) has a different name. The option is sourceHighlighter. The attribute is source-highlighter.

**Comment by DanielSWolf** [comment]
Thanks for all your help! Both the attribute and the option are working for me now. I must have placed the attribute into the wrong XML element by accident.

Still, one thing puzzles me: The .adoc document I'm processing contains this line in its header:

```adoc
:source-highlighter: highlight.js
```

When I run the command-line `asciidoctor` tool without specifying any attributes, it reads the `source-highlighter` attribute from the document itself and applies syntax highlighting. Why does the Maven plugin require this attribute to be set from the `pom.xml` rather than evaluating the document itself, the way the command-line tool does?

**Comment by mojavelinux** [comment]
@DanielSWolf That to me is an indication of a bug. If an attribute is specified via the API, it overrides the value in the document. However, if you don't specify it, then the document setting should win.

**Comment by abelsromero** [comment]
The initialization of `sourceHighlighter` [here](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L111) with `""`, caused that the value in the document was overridden precisely `""`.
Just setting it to null fixes the issue.
