### ISSUE TITLE
maven-plugin-annotation dependency should be scope provided

### ISSUE THREAD

**Issue by khmarbaise** [asciidoctor/asciidoctor-maven-plugin#240]
http://maven.apache.org/plugin-tools/maven-plugin-plugin/examples/using-annotations.html#POM_configuration
``` xml
<dependency>
      <groupId>org.apache.maven.plugin-tools</groupId>
      <artifactId>maven-plugin-annotations</artifactId>
      <version>3.4</version>
      <scope>provided</scope><!-- annotations are needed only to build the plugin -->
</dependency>
```

**Comment by abelsromero** [comment]
If I understand it right, this is required to generate the plugin.xml and plugin-help.xml descriptors in the jar, but not for the plugin execution?

**Comment by khmarbaise** [comment]
Yup...The annotations are only used during the run of `maven-plugin-plugin` which generates the plugin.xml descriptor from the annotations. For the run of the plugin they are not needed. This is reason why they can be defined scope provided.

**Comment by abelsromero** [comment]
Thanks :) I am learning so much today!
I want to test in my local first, to see if the XMLs are all exactly the same, and then I'll merge.

**Comment by abelsromero** [comment]
Note is not mistrust, but this has never been changed and I want to be 150% sure nothing breaks

**Comment by khmarbaise** [comment]
I don't take it as mistrust etc. I understand that you really check things to be sure not to break things...But on the other hand you seemed to not trusting your tests (IT's included) if no IT fails  it should mean it works shouldn't that mean that ? ;-)

**Comment by abelsromero** [comment]
Good observation. 
Summary is; yes, we need more IT tests (WIP thing) but no, not really that they are not good enough. Is more personal curiosity and desire to see some of the under-the-hood details of Maven.

**Comment by khmarbaise** [comment]
Sure it's always good to learn...and understand things...

**Comment by abelsromero** [comment]
100% equal except for:
- a comment that says `maven-plugin-tools 3.2`
- the dependency, which does not appear obviously
- the order in which mojos appear

So, nothing to fear 👍

**Comment by khmarbaise** [comment]
Sorry but I don't understand your comments? Which comment says this? The order in which mojos appear ?

**Comment by abelsromero** [comment]
The jar contains two descriptors, plugin.xml and plugin-help.xml (funny enough they duplicate a lot of data). Comparing each one respectively with previous builds I only found those differences.
I also included in the comparison the merging of versions to 3.4.

**Comment by khmarbaise** [comment]
Ah now I get it...plugin.xml is for runtime and injections (plexus & guice) whereas plugin-help.xml is for help output via `mvn asciidoctor:help...`...
