### ISSUE TITLE
Maven Configuration in appveyor.yml does not use the cache

### ISSUE THREAD

**Issue by khmarbaise** [asciidoctor/asciidoctor-maven-plugin#244]
Based on the docs maven should be configured to use the local build cache to prevent downloading of all artifacts for every build. 
`-Dmaven.repo.local=C:\maven`

**Comment by khmarbaise** [comment]
The cache is cleaned every time the `appveyor.yml` changes. sounds like a very good strategy (http://www.appveyor.com/docs/build-cache).

**Comment by mojavelinux** [comment]
What about the `C:\Users\appveyor\.m2` folder? Isn't that where the cache is located?

**Comment by mojavelinux** [comment]
Oh, I see...you are configuring the location of the cache. It seems like it would be better to use the cache under the user's folder and just mark that as a cache folder.

**Comment by khmarbaise** [comment]
If this is the correct location it would be simpler to configure this in `appveyor.yml` and remove the `-Dmaven.repo.local=C:\maven` from the maven calls.

**Comment by mojavelinux** [comment]
:+1:

**Comment by abelsromero** [comment]
Closing with PR https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/272
