### ISSUE TITLE
Why running clean package / verify separately

### ISSUE THREAD

**Issue by khmarbaise** [asciidoctor/asciidoctor-maven-plugin#248]
The `appveyor.yml` configuration contains:
```
build_script:
  - mvn clean package -B -Dmaven.test.skip=true
test_script:
  - mvn -Prun-its verify -B
```
and `.travis.yml ` somthing similar:
```
install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn -Prun-its verify jacoco:report
```
on the first glance they are not the same those maven calls...
But why not simply using:
```
script:
 - mvn -B -V -Prun-its clean verify jacoco:report
```
This would mean in `.travis.yml`
``` 
install: true
script:
 - mvn -B -V -Prun-its clean verify jacoco:report
``` 
and in `appveyor.yml` it should look like this:
```
build_script:
  - mvn -B -Prun-its clean verify jacoco:report
```

If you call `mvn package` and afterwards `mvn verify` you run all life cycle parts including packaging double ?

**Comment by abelsromero** [comment]
Conceptually I like to separate prepare/build/test steps, but also I think that making the process simpler and quicker is a good thing.
In my experience when something fails I just scroll to the bottom to see the message and then scroll up looking for an exception, it doesn't make much difference where it failed.

**Comment by mojavelinux** [comment]
Exactly. I think the "best practice" is to make it clear which step fails. First, check if it can compile. If that works, check if the tests pass. It's probably over-complicating the situation though. But just so you understand the reasoning behind it.

**Comment by khmarbaise** [comment]
Yes it is best practices but it does not make things better...it slows down build time...produces more logs to read and it produces not more valuable information...and in the end it would make more sense to simply do `mvn -Prun-its clean verify`.....with a better result (shorter and faster with the same information)...I understand the reasons behind very well (If we were in C/C++ etc. it would make sense to separate that, but in Java and Maven it does not make sense...) furthermore the scripts (travis.yml and appveyor.yml) are doing different things which makes them not comparable etc.

**Comment by mojavelinux** [comment]
:+1: 

I think this is one of those cases where someone proposed a "best practice" that wasn't in fact the best practice...and we all copied it. Glad to have these assumptions challenged!

**Comment by mojavelinux** [comment]
> the scripts (travis.yml and appveyor.yml) are doing different things which makes them not comparable etc.

Especially good point!

**Comment by abelsromero** [comment]
If you don't mind I'll like to take on this one
