### ISSUE TITLE
maven-plugin-plugin will be executed twice during build

### ISSUE THREAD

**Issue by khmarbaise** [asciidoctor/asciidoctor-maven-plugin#250]
The problem is based on defining the `maven-plugin-plugin` in the build block instead of using `pluginManagement` to define the version and it's parameters. The binding is already done by the [default life cycle](http://maven.apache.org/ref/3.3.9/maven-core/default-bindings.html#Plugin_bindings_for_maven-plugin_packaging)

**Comment by abelsromero** [comment]
I checked the XML files (just in case) and eveything is fine. I'll merge it later if no one has anything to add.
