### ISSUE TITLE
getting "org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: (LoadError) library `strscan' could not be loaded: java.lang.OutOfMemoryError: PermGen space" error

### ISSUE THREAD

**Issue by faizanzaver** [asciidoctor/asciidoctor-maven-plugin#262]
Hi guys,

I am facing an OutOfMemoryError while running asciidoctor-maven-plugin
in my project.
Any ideas what might be wrong?

This is the console output.

[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building <project name> 5.2.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ <project name> ---
[INFO] Deleting D:\GIT Dev\<project name>\target
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.13:check (checkstyle_all_sources) @ <project name> ---
[INFO] 
[INFO] 
[INFO] >>> maven-pmd-plugin:3.1:check (pmd) @ <project name> >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.1:pmd (pmd) @ <project name> ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] 
[INFO] <<< maven-pmd-plugin:3.1:check (pmd) @ <project name> <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.1:check (pmd) @ <project name> ---
[INFO] 
[INFO] 
[INFO] --- maven-pmd-plugin:3.1:cpd (pmd) @ <project name> ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] 
[INFO] --- cxf-codegen-plugin:3.0.9:wsdl2java (default-cli) @ <project name> ---
[INFO] 
[INFO] --- copy-rename-maven-plugin:1.0.1:copy (copy-file) @ <project name> ---
[INFO] Copied D:\GIT Dev\<project name>\<project name>-release-notes.txt to D:\GIT Dev\<project name>\target\<project name>-5.2.0-release-notes.txt
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ <project name> ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ <project name> ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 166 source files to D:\GIT Dev\<project name>\target\classes
[WARNING] /D:/GIT Dev/<project name>/src/main/java/com/ing/cbp/commons/owasp/OwaspValidator.java: Some input files use unchecked or unsafe operations.
[WARNING] /D:/GIT Dev/<project name>/src/main/java/com/ing/cbp/commons/owasp/OwaspValidator.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ <project name> ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ <project name> ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 46 source files to D:\GIT Dev\<project name>\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ <project name> ---
[INFO] Surefire report directory: D:\GIT Dev\<project name>\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Tests run: 213, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.745 sec - in TestSuite

Results :

Tests run: 213, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ <project name> ---
[INFO] Building jar: D:\GIT Dev\<project name>\target\<project name>-5.2.0.jar
[INFO] 
[INFO] --- build-helper-maven-plugin:1.9.1:attach-artifact (attach-artifacts) @ <project name> ---
[INFO] 
[INFO] --- swagger2markup-maven-plugin:0.9.3:process-swagger (default-cli) @ <project name> ---
reading from D:\GIT Dev\<project name>\target\generated-docs\swagger2\swagger2.json
[INFO] overview.adoc was written to: D:\GIT Dev\<project name>\target\generated-docs\asciidoc
[INFO] Added path operation 'GET /api/v1/app/translations/{language}' to tag 'translation-controller'
[INFO] Path processed: GET /api/v1/app/translations/{language}
[INFO] paths.adoc was written to: D:\GIT Dev\<project name>\target\generated-docs\asciidoc
[INFO] definitions.adoc was written to: D:\GIT Dev\<project name>\target\generated-docs\asciidoc
[INFO] 
[INFO] --- asciidoctor-maven-plugin:1.5.3:process-asciidoc (default-cli) @ <project name> ---
io/console not supported; tty will not be manipulated
/C:/Users/FaizanC/.m2/repository/org/jruby/jruby-complete/1.7.21/jruby-complete-1.7.21.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `require':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:10 min
[INFO] Finished at: 2016-08-17T11:27:06+05:00
[INFO] Final Memory: 80M/969M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (default-cli) on project <project name>: Execution default-cli of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: (LoadError) library `strscan' could not be loaded: java.lang.OutOfMemoryError: PermGen space -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by abelsromero** [comment]
On top of the `OutOfMemoryError: PermGen` seems there are some issues with mising Ruby modules. Not 100% sure if this is related, but I've noticed you're using a pre v1.x swagger2markup-maven-plugin plugin, so I'd recommend two actions:
- Increase PermGen configuration and run with -e flag to get more information.
- Update the swagger plugin to the last version and see if it still happends: note that last versions are only published in Bintray and with a different groupId. I could build a example with this https://github.com/Swagger2Markup/swagger2markup-maven-project-template.

**Comment by faizanzaver** [comment]
Increasing the PermGen configuration solved the issue.
set MAVEN_OPTS=-Xmx2048m -XX:MaxPermSize=2048m

and the mising Ruby modules warning disappeared too.

Thank you for your time :)

**Comment by abelsromero** [comment]
I am glad it was solved. Just out of curiosity and to be able to identify possible mem leaks, have you been able to narrow the XX:MaxPermSize to the point it fails?

**Comment by faizanzaver** [comment]
Alright.
I got the same issue with 
set MAVEN_OPTS=-Xmx1024m -XX:MaxPermSize=1024m
so I guess 2048m is fine.

Plus this memory leak issue was in a specific project as others were working fine without any increasing the memory. So it is project dependent because when I run only this plugin from maven, I get no error But it occurs on the complete mvn clean install.
