### ISSUE TITLE
Accent not in good encoding using UTF-8 adoc

### ISSUE THREAD

**Issue by funregis** [asciidoctor/asciidoctor-maven-plugin#263]
The accent are not rendered in UTF-8 encoding in the generated HTML by maven plugin Asciidoctor 1.5.3

For this adoc , if you open it in UTF-8 you see the word "réponse"

[response-fields.adoc.txt](https://github.com/asciidoctor/asciidoctor-maven-plugin/files/449231/response-fields.adoc.txt)

the generated html for this part is like that

`<h3 id="__strong_description_de_la_rÃponse_strong_2">2.4. <strong>description de la rÃ©ponse</strong></h3>`

the word "rÃ©ponse" should be "réponse"

**Comment by abelsromero** [comment]
The file seems to be already corrupted, when I open it as UTF-8 it already shows the wrong characters (using Notepad++ on Windows 8.1).
```
=== *description de la rÃ©ponse*
````
Can you zip it from your drive and upload it again please?

**Comment by funregis** [comment]
Sorry you're right, the problem comes from the use of spring rest who generates the .doc with the wrong encoding.

**Comment by abelsromero** [comment]
No worries, glad it was solved.
