### ISSUE TITLE
Failed includes do not break the build

### ISSUE THREAD

**Issue by bannmann** [asciidoctor/asciidoctor-maven-plugin#268]
Right now, when an include file could not be found, I get a warning message:
```
asciidoctor: WARNING: example.adoc: line 20: include file not found: C:/my/folder/src/main/java/example/SplineReticulator.java
asciidoctor: WARNING: example.adoc: line 22: no callouts refer to list item 1
```
Now suppose I have an include to SplineReticulator.java and a developer renames that source file without being aware of the include. This will break the documentation, and nobody will notice until it's too late (e.g. after having made the release tag).

Similarly, if the file itself is still there, but a developer moves the method with the callout to another file (or removes the callout due to refactoring), the same problem occurs.

Thus, I want the option to have my maven build fail if any include or callout reference is broken. Can this be implemented in the maven plugin (or in asciidoctor core)?

**Comment by bannmann** [comment]
I just discovered issue #261, so I guess this issue can be closed as a duplicate.

**Comment by abelsromero** [comment]
As you say, I will close the as duplicated. And thanks for you'r feedback, even when duplicated it's always to good to get feedback and detailed use cases.
