### ISSUE TITLE
Exclude docinfo files by default

### ISSUE THREAD

**Issue by ge0ffrey** [asciidoctor/asciidoctor-maven-plugin#269]
With for example foo-docinfo.html and foo-docinfo-footer.html we can add a snippet of html code in asciidoctor to the generated html. The plugin shouldn't copy these as resources in the output directory by default.

**Comment by mojavelinux** [comment]
I agree!

The following files should be ignored:

* docinfo.html
* docinfo-header.html
* docinfo-footer.html
* *-docinfo.html
* *-docinfo-header.html
* *-docinfo-footer.html

(docinfo-header is reserved for future use, but not yet enabled)

**Comment by ge0ffrey** [comment]
I tried workaround around it with this config in the plugin, but that doesn't work for some reason:

              <goals>
                <goal>process-asciidoc</goal>
              </goals>
              <configuration>
                <resources>
                  <resource>
                    <directory>src/main/asciidoc</directory>
                    <excludes>
                      <exclude>**/docinfo.html</exclude>
                      <exclude>**/docinfo-header.html</exclude>
                      <exclude>**/docinfo-footer.html</exclude>
                      <exclude>**/*-docinfo.html</exclude>
                      <exclude>**/*-docinfo-header.html</exclude>
                      <exclude>**/*-docinfo-footer.html</exclude>
                    </excludes>
                  </resource>
                </resources>

I'll investigate, to see if I find a workaround and maybe send in a PR to fix this issue upstream.

**Comment by abelsromero** [comment]
Resource filtering has not been published yet, if you want to use it you'll need to download the sources and compile them locally.
With the current published version there's no way to accomplish what you need. Only work-arround I can think of is deleting the files after they are generated using another plugin.

**Comment by ge0ffrey** [comment]
PR send: https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/270
