### ISSUE TITLE
Is the imagesDir option overridable by the .adoc files?

### ISSUE THREAD

**Issue by sjoerdtalsma** [asciidoctor/asciidoctor-maven-plugin#294]
I seem to be experiencing the opposite issue from #68 : 

- There is some directory structure containing `.adoc` files.
- Images are in `images` directory of the 'relative root' of that structure.
- The `.adoc` files contain `:imagesdir: ./images`, `:imagesdir: ../images` or even `:imagesdir: ../../images` references.
- The `preserveDirectories` option is `true` obviously.

Even when I _don't_ supply an `imagesDir` option to the maven plugin, it _defaults_ to `images`.
This seems to override the explicit location in the `.adoc` files.

I cannot imagine being the first with this issue, so it may well be that I'm doing something wrong...

**Comment by sjoerdtalsma** [comment]
Example `.adoc` header:
```asciidoc
= Document title
Sjoerd Talsma <my@email.address>
v1.0.0
:imagesdir: ../images
```

Example maven config:
```xml
<configuration>
   <preserveDirectories>true</preserveDirectories>
   <backend>html5</backend>
   <attributes>
      <docVersion>${project.version}</docVersion>
      <!-- Is this attribute 'unsettable'? it defaults to 'images': 
              <imagesdir>images</imagesdir> -->
   </attributes>
</configuration>
```

**Comment by abelsromero** [comment]
> This seems to override the explicit location in the .adoc files.

You are right and that's clearly an issue. `images` is set by default here  https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L111.
Initialising it to null will fix the problem.

Since attributes passed in the pom take precedence over the ones set in the document, you cannot set them in the document.
To be 100% clear, once fixed, if you set imagesdir to `<imagesDir>` (in <configuration>) or as `<imagesdir>` (under <attributes>), `:imagesdir:` in documents will be ignored.
Also, this won't change the default behaviour, the underlying Asciidoctor core will still use images as default.

**Comment by sjoerdtalsma** [comment]
Want me to make a PR to initialize to `null` if that's the accepted resolution?

**Comment by abelsromero** [comment]
> Want me to make a PR to initialize to null if that's the accepted resolution?

No problem at all, just make sure all test pass. I am pretty sure this should fix the problem, but you can never be sure.


> // use a string because otherwise html doc uses absolute path

Don't worry, that comes from old versions in which imagesDir was a File which causes issues.

**Comment by abelsromero** [comment]
My mistake, I run a test on the shell and checked the manual http://asciidoctor.org/docs/user-manual/#setting-the-location-of-images. `imagesdir` is empty by default.

So, in order to keep compatibility with current behaviour we would need to add a new option, something like a boolean called `allowDocumentImagedir`. That would allow to skip the configuration of the attribute.

Honestly I am not inclined to adding more options, I'd rather honor the original treatment but since this breaks compatibility, this would need to be added to 1.6.0.

**Comment by mojavelinux** [comment]
To be honest, it was incorrect for the Maven plugin to set a default value for the images directory. If we were to implement a default, it should be done in core.

However, there is a value you can use to restore the default behavior. Just set the value to `@`. A trailing `@` symbol in the value of the attribute indicates that the document should be allowed to override the value.

See http://asciidoctor.org/docs/user-manual/#attribute-assignment-precedence

**Comment by mojavelinux** [comment]
> Honestly I am not inclined to adding more options, I'd rather honor the original treatment but since this breaks compatibility

We should do this. I'd even say before 1.6.0. Most people set imagesdir anyway, so it's not a huge concern. And they can fix their build simply by adding it if they were relying on the default value.

**Comment by sjoerdtalsma** [comment]
>However, there is a value you can use to restore the default behavior. Just set the value to @. A trailing @ symbol in the value of the attribute indicates that the document should be allowed to override the value.

@mojavelinux Thanks! I'll try that as an initial workaround tomorrow. It may save the day for us with hte current version already (documentation generation is inherited for all our projects from a central maven tile; poor man's delegation in the maven world)

**Comment by sjoerdtalsma** [comment]
@abelsromero 
> Honestly I am not inclined to adding more options

I share your inclination; could a default change from `images` to `images@` be enough?
If I understand @mojavelinux ' comments correctly, this provide both a (backward compatible) default value, but allows override by the documents.

**Comment by mojavelinux** [comment]
@sjoerdtalsma Good suggestion. That could indeed work. I'm open to that if you feel like getting rid of it altogether it too drastic. Though it's still strange that the Maven plugin doesn't work like all other plugins and core itself.

**Comment by sjoerdtalsma** [comment]
I decided to keep the default and just add the `@` to make it overridable.
This has the least impact on people currently using the plugin, while still fixing the bug.
All tests pass and I (manually) verified the `:imagesdir:` is now overridable by documents.
So merging #295 should resolve this issue.

**Comment by abelsromero** [comment]
:+1: Perfect solution, once again, Asciidoctor core saves the day!
I'll merge and close this it right now.

Still, for 1.6.0 we should respect the original behavior. @sjoerdtalsma do you want to open an issue for that? I will tag it for 1.6.0 tracking.

**Comment by sjoerdtalsma** [comment]
@abelsromero Thanks for merging this so quickly :smile: 

Of course I can open a new issue to respect the original behaviour, but just to clarify:
It's about removing the whole `imagesDir` configuration setting in the first place?
After all, the default shouldn't have been there and it can still be set in the `<attributes>` setting.

**Comment by abelsromero** [comment]
> After all, the default shouldn't have been there and it can still be set in the <attributes> setting.

I don't like the duplicity of `imagesdir` and other attributes that we have now. But I think it's nice to have the most common options there. Specially helps new users with IDE auto-completion.

What I am thinking for 1.6.0 is just removing the default `images@` path keeping the current options. Oh! and renaming it to `imagesdir`, the closer to the original the better.

**Comment by sjoerdtalsma** [comment]
@abelsromero Gotcha! I'll open a new issue for that.
