### ISSUE TITLE
Issue with execution configuration?

### ISSUE THREAD

**Issue by rmannibucau** [asciidoctor/asciidoctor-maven-plugin#302]
Hi guys,

using maven 3.5.0 if you have a configuration for the execution and not the plugin then it is ignored.

**Comment by abelsromero** [comment]
Apologies, but I am not sure I understand the case.

With `a configuration for the execution and not the plugin` you mean when all configuration is enclosed in a `<execution>` block?
If so, I run a couple of tests with https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-example. Moving the configuration in `<configuration>` to the execution block and I had no problems.

Please, if I understood it wrong, just clarify it, or point me to a example repo.

**Comment by rmannibucau** [comment]
Hi Abel,

yes exactly. I was surprised as well since i used it for pdf but here it is a plain html5 rendering with last maven version. Didn't investigate more than checking attributes was not initialized. Just copying the execution#configuration in the plugin#configuration worked well.

**Comment by abelsromero** [comment]
I tried putting all configuration in the <configuration> and all in the <execution> blocks, an in both cases it worked fine.
I even added a custom attribute to validate it was replaced in the text, and it was.

But I don discard any possible issue. Could it be, the project in a multi module project? maybe inheriting some configuration?

**Comment by rmannibucau** [comment]
It is using this layout: fakeparent (not known from child) -> parent -> modulewithplugin

Will try tomorrow to reproduce it in a sample

**Comment by rmannibucau** [comment]
Ok found what I did wrong:

    mvn asciidoctor:http

versus

    mvn asciidoctor:http@doc

Sorry for the noise
