### ISSUE TITLE
Genearting reveal js how to modify style settings?

### ISSUE THREAD

**Issue by ehmkah** [asciidoctor/asciidoctor-maven-plugin#308]
I am unsure where to ask the folllowing question because, it has something to do with asciidoctor reveal.js and maven integration. https://github.com/asciidoctor/asciidoctor-reveal.js/issues/137 

I need to fix the settings for the speaker-notes screen. For me a bigger notes section would be cool.

the following approaches are working but are overwritten which each build

If I change the width of #speaker-controls css attribute in chrome
manipulate the notes.html file which is generated by maven
So how could I make this change persistent when the presentation is generated?

**Comment by ehmkah** [comment]
solution is to upgrade to newest version of revealjs at least 3.5.0 and than you can see something like https://cloud.githubusercontent.com/assets/629429/21808439/b941eb52-d743-11e6-9936-44ef80c60580.gif

**Comment by abelsromero** [comment]
> I am unsure where to ask the folllowing question because, it has something to do with asciidoctor reveal.js and maven integration. asciidoctor/asciidoctor-reveal.js#137

No problem at all! How else are we going to find new ways to improve?
