### ISSUE TITLE
outputFile doesn't seem to work

### ISSUE THREAD

**Issue by ericis** [asciidoctor/asciidoctor-maven-plugin#320]
I've tried adding `<outputFile>` to the root `<configuration><attributes>`, `<execution>...<configuration>` and `<execution>...<configuration>...<attributes>`  sections with no success.

```
        <asciidoctor.maven.plugin.version>1.5.5</asciidoctor.maven.plugin.version>
        <asciidoctorj.pdf.version>1.5.0-alpha.16</asciidoctorj.pdf.version>
        <asciidoctorj.version>1.5.6</asciidoctorj.version>
        <jruby.version>1.7.26</jruby.version>
```

**Comment by ericis** [comment]
I had to upgrade to 1.5.6 of the plugin.
`<asciidoctor.maven.plugin.version>1.5.6</asciidoctor.maven.plugin.version>`

**Comment by abelsromero** [comment]
Still, I think you found something...
Just setting a simple name(`my_file.html`) generates the file in the root of the project.
And it ignores `outputDirectory`, even when the tests for that work.
Have you experiened the same?

**Comment by ericis** [comment]
Sorry I missed this @abelsromero. I hadn't tried. Maybe open a new issue (if you haven't already)

**Comment by abelsromero** [comment]
Don't worry, false alarm, eveything works fine.
