### ISSUE TITLE
`site` goal - self-closed attributes (eg. <sectnums/>) do not work

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#330]
All attributes need to be set in a full form.
But some do not have value and should be able to be set using self-closed form.
For example `sectnums` needs to be set as `<sectnums>true</sectnums>`.

**Comment by mojavelinux** [comment]
That's probably because the site plugin does not implement the workaround that we use in the main plugin (and I'm not sure if it's even possible).

**Comment by abelsromero** [comment]
I am aware, I am just writting some issues I found yesterday.
Maybe cannot be fixed, but at least, we can try.

**Comment by abelsromero** [comment]
Just tested and has been fixed with the changes in 2.0.0. Now the site uses the same code as the Mojo to set attributes.
