### ISSUE TITLE
how to get images working for generated html docs in a multi-module site.

### ISSUE THREAD

**Issue by ymmark0** [asciidoctor/asciidoctor-maven-plugin#333]
I've using the maven site plugin to generate site docs which include static documentation generated via asciidoc.  Each module in the site has a src/site/asciidoc folder, in which I have the relevant a.doc and also a /src/site/asciidoc/images directory containing the images.

The site is building correctly except for the images and my experimentation hasn't produced results.
In the top level pom I have:
```
<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.7</version>
                    <configuration>
                        <!-- disable generateReports if you don't want to include the built-in reports -->
                        <generateReports>true</generateReports>
                        <generateSitemap>true</generateSitemap>
                        <relativizeDecorationLinks>false</relativizeDecorationLinks>
                        <locales>en</locales>
                        <inputEncoding>UTF-8</inputEncoding>
                        <outputEncoding>UTF-8</outputEncoding>
                        <asciidoc>
                            <sourceDirectory>${project.basedir}/src/site/asciidoc</sourceDirectory>
                            <attributes>
                                <imagesdir>./images</imagesdir>
                            </attributes>
                        </asciidoc>
                        <moduleExcludes>
                            <asciidoc>**/_*.adoc</asciidoc>
                        </moduleExcludes>
                    </configuration>
                    <dependencies>
                        <dependency><!-- add Asciidoctor Doxia Parser Module -->
                            <groupId>org.asciidoctor</groupId>
                            <artifactId>asciidoctor-maven-plugin</artifactId>
                            <version>1.5.6</version>
                        </dependency>
                        <dependency>
                            <groupId>org.jruby</groupId>
                            <artifactId>jruby-complete</artifactId>
                            <version>9.1.15.0</version>
                        </dependency>
                        <!-- Comment this section to use the default AsciidoctorJ artifact provided by the plugin -->
                        <dependency>
                            <groupId>org.asciidoctor</groupId>
                            <artifactId>asciidoctorj</artifactId>
                            <version>1.5.6</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <!-- used for multiproject builds -->
                        <execution>
                            <id>attach-descriptor</id>
                            <goals>
                                <goal>attach-descriptor</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
```

I've also tried 
```
<configuration><asciidoc><imagesDir> 
```
(without attributes).
AFAICS, images should be the default anyway and it should simply copy the images to target, however that's not happening.  Is there something obvious I'm missing?

**Comment by abelsromero** [comment]
I think that by default, resources should be in `src/site/resources`

**Comment by abelsromero** [comment]
I am thinking we need to document that in the README. The `site` goal does not allow customizing resources to copy.
I'd bet money the site-plugin copies eveything inside the `${siteDirectory}/resources` path but could not find anything in the [docs](https://maven.apache.org/plugins/maven-site-plugin/). We'll have to look at the code to confirm it.

**Comment by ymmark0** [comment]
thanks that would be really appreciated - I'll try migrating to resource and see what happens.

**Comment by abelsromero** [comment]
Indeed, confirmed!
The maven-site-plugin copies everything under ${siteDirectory}/resources.
If you need to add more. First I'd advise to review the structure to keep everything inside one master/catalog directory. If this is not possible, you can use the maven-resource-plugin to copy them.

Sire note: the site-plugin has a list of possible source directories. But only allows to set 1 using the siteDirectory property:
https://gitbox.apache.org/repos/asf?p=maven-doxia-sitetools.git;a=blob;f=doxia-site-renderer/src/main/java/org/apache/maven/doxia/siterenderer/DefaultSiteRenderer.java;h=f7abb91070be3c6d4053f2089bb2e9c104f93dc4;hb=HEAD#l1031

**Comment by abelsromero** [comment]
I created this PR https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/336.
I would really appreciate if you could have a look at it and give your opinion about it.

**Comment by abelsromero** [comment]
Documentation was already expanded to explain this topic. If any other doubt remains, feel free to reopen.
