### ISSUE TITLE
Update plugin dependences

### ISSUE THREAD

**Issue by slachiewicz** [asciidoctor/asciidoctor-maven-plugin#340]
Remove inheritance from org.sonatype.oss:oss-parents (https://github.com/sonatype/oss-parents) - every project should define its own parent-pom/depenedencyManagement

Lock required plugins in pluginManagement section of pom.xml

**Comment by abelsromero** [comment]
Ircc this is for publishing into maven central, but could be wrong. This is one of those setting that "works" and never has been reviewed 😆 .
Is there any documentation to check that and make sure we don't affect the publishing?
