### ISSUE TITLE
Index not generated for pdf output

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-maven-plugin#344]
My document ends with this section:

```
[Index]
== Index

```

The backend is set to `docbook`. I use a custom theme. I have a term in my document like ((example)) which should turn into an index entry.

The pdf shows no index being generated. Any idea?

**Comment by abelsromero** [comment]
I understand you have some `docbook` to `PDF` also right?
Since there're a few moving parts here, can you provide an example for me to play with? This would really help a lot.

**Comment by seinecle** [comment]
I had put `docbook `instead of `pdf `in te backend by ignorance. I reverted to `pdf`, but same result: no index in the pdf output.
In the following gist, you'll find:
- an example of a document in asciidoc. It has two terms between double brackets, and a final section styled as `[index]
- the relevant section of my pom.xml

I hope this is helps reproduce the issue? I can add more content as needed.

**Comment by mojavelinux** [comment]
I just tried this using the asciidoctor-pdf example in https://github.com/asciidoctor/asciidoctor-maven-examples. If I add an index entry (such as `((return)) statement`), then add a level-1 index special section at the end, the index is generated. Can you reproduce?

```
= Example Manual

...

((return)) statement

...

[index]
== Index
```

**Comment by seinecle** [comment]
I cloned the example from the github repo and can't reproduce. The index section remains empty. Maybe due to where I place the index section? I put it right at the bottom of the adoc file, like this:

`
...
== Source Code and Syntax Highlighting

This section shows some code highlighting examples.

include::subdir/_code_examples.adoc[]

[Index]
== Index
`

(and yes I did not forget to put some terms in double brackets like ((return)).

Could it be that the maven build refers to the wrong version of asciidoctorj.pdf, even if I version `1.5.0-alpha.16` is specified?

FWIW, I use NetBeans, Java 8 and run on Windows 7.

**Comment by seinecle** [comment]
I run maven from NetBeans. The console says:
```

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Asciidoctor PDF Maven example 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- asciidoctor-maven-plugin:1.5.6:process-asciidoc (generate-pdf-doc) @ asciidoctor-pdf-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Rendered C:\Users\levallois\Google Drive\open\NetBeans Projects\asciidoctor-maven-examples\asciidoctor-pdf-example\src\docs\asciidoc\example-manual.adoc
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ asciidoctor-pdf-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\levallois\Google Drive\open\NetBeans Projects\asciidoctor-maven-examples\asciidoctor-pdf-example\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ asciidoctor-pdf-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ asciidoctor-pdf-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\levallois\Google Drive\open\NetBeans Projects\asciidoctor-maven-examples\asciidoctor-pdf-example\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ asciidoctor-pdf-example ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ asciidoctor-pdf-example ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ asciidoctor-pdf-example ---
[INFO] Building jar: C:\Users\levallois\Google Drive\open\NetBeans Projects\asciidoctor-maven-examples\asciidoctor-pdf-example\target\asciidoctor-pdf-example-1.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ asciidoctor-pdf-example ---
[INFO] Installing C:\Users\levallois\Google Drive\open\NetBeans Projects\asciidoctor-maven-examples\asciidoctor-pdf-example\target\asciidoctor-pdf-example-1.0.0-SNAPSHOT.jar to C:\Users\levallois\.m2\repository\org\asciidoctor\maven\asciidoctor-pdf-example\1.0.0-SNAPSHOT\asciidoctor-pdf-example-1.0.0-SNAPSHOT.jar
[INFO] Installing C:\Users\levallois\Google Drive\open\NetBeans Projects\asciidoctor-maven-examples\asciidoctor-pdf-example\pom.xml to C:\Users\levallois\.m2\repository\org\asciidoctor\maven\asciidoctor-pdf-example\1.0.0-SNAPSHOT\asciidoctor-pdf-example-1.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.339 s
[INFO] Finished at: 2018-04-24T10:00:43+02:00
[INFO] Final Memory: 66M/595M
[INFO] ------------------------------------------------------------------------

```

**Comment by seinecle** [comment]
I guess I must do something really silly somewhere. I try running it from the CLI and report here.

**Comment by seinecle** [comment]
It makes no difference. I'll try running it from a different PC.

**Comment by seinecle** [comment]
I ran it on a different PC (same OS), same result. I attach the output pdf for reference. I must be doing something wrong somewhere.
[example-manual.pdf](https://github.com/asciidoctor/asciidoctor-maven-plugin/files/1941820/example-manual.pdf)

**Comment by mojavelinux** [comment]
The only thing I can think is that there is another version of Asciidoctor PDF floating around. Have you ever installed the Ruby version of Asciidoctor PDF? (Check if $GEM_PATH is defined and if there's anything there if so).

**Comment by seinecle** [comment]
I don't see $GEM_PATH in my system variables. Hm.

**Comment by seinecle** [comment]
It was hidden in plain sight. I was writing [Index] instead of [index]. See above. Sigh.

**Comment by mojavelinux** [comment]
OMG! Mystery solved!

I usually have a good eye for this sort of thing. I can't believe I missed it!

This calls for a :beer:

**Comment by seinecle** [comment]
It's 7am here but I hold it for tonight!
