### ISSUE TITLE
`outputFile` uses project root path as target directory

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#348]
**Current behaviour:**
For example, when using only `outputFile` to set only the filename, the output is generated in the project root instead of the default `outputDirectory`.

**Expected behaviour:**
In my opinion plugin should append `outputFile` to `outputDirectory`:
* if `outputDirectory` is not set, output should be placed under `${project.build.directory}/generated-docs` if the path is relative (e.g. simple filename).
* if `outputDirectory` is set and `outputFile` contains a relative path, this should be appended to `outputDirectory` value.
* if `outputDirectory` is set and `outputFile` contains an absolute path, `outputFile` overrides `outputDirectory` same as now.

**Comment by kingsleykumar** [comment]
Hi, Any update on this ? Any workaround to place the file in the outputDirectory instead of project root path ? Thanks.
