### ISSUE TITLE
imagesDir does not behave like imagesdir

### ISSUE THREAD

**Issue by michael-o** [asciidoctor/asciidoctor-maven-plugin#353]
The default Asciidoctor (`asciidoctor(1)`) configuration says that `imagesdir` is by default empty. Yet the Maven Plugin does change this value making it deviate from the wellknown standard. Moreover, I cannot reset this value to empty: `<imagesDir />` because the Java code checks for `null` only, but the selfclosing element creates an empty string. One has to apply a hack: `<imagesDir>.</imagesDir>`.

I expect the value to be empty -- as per default.

**Comment by abelsromero** [comment]
You are totally right, this is scheduled for 1.6.0: https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/296.
We are saving non backward compatible changes for 1.6.0, but if there's enough demand we could consider adding this to a previous version.

**Comment by abelsromero** [comment]
I am closing this as duplicated.
