### ISSUE TITLE
Getting this 'org.asciidoctor:asciidoctor-maven-plugin': Plugin requires Maven version 3.0.0'

### ISSUE THREAD

**Issue by mscsf15m027** [asciidoctor/asciidoctor-maven-plugin#355]
Hi everyone,

When i clone the repository it works fine. But when i run this command

`mvn install`

It shows an error.

`Error resolving version for 'org.asciidoctor:asciidoctor-maven-plugin': Plugin requires Maven version 3.0.0`

I replaced the maven version in pom.xml file.

```
<groupId>org.asciidoctor</groupId>
<artifactId>asciidoctor-maven-plugin</artifactId>
<version>3.0.0</version>
```

But now this error is occurring.

```
Error building POM (may not be this project's POM).
Project ID: org.asciidoctor:asciidoctor-maven-plugin
POM Location: /home/rana/.m2/repository/org/asciidoctor/asciidoctor-maven-plugin/3.0.0/asciidoctor-maven-plugin-3.0.0.pom

Reason: Not a v4.0.0 POM. for project org.asciidoctor:asciidoctor-maven-plugin at /home/rana/.m2/repository/org/asciidoctor/asciidoctor-maven-plugin/3.0.0/asciidoctor-maven-plugin-3.0.0.pom
```

Please help me in resolving this problem.

**Comment by abelsromero** [comment]
I suspect the issue is related to your local version of Maven.
Can you run `mvn -v` and share the output. If it's not the latest (3.5.4) I highly recommend to upgrade to it.

**Comment by abelsromero** [comment]
Could you check this?
