### ISSUE TITLE
`NullPointerException` when enabling logHandler.outputToConsole

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#366]
_version: 1.5.7_

Some Asciidoctor messages cause a `NullPointerException` when `outputToConsole` is set to true.

This is due to the fact that this messages does not contain "cursor" element and the formatter fails.

See https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/363#issuecomment-420963429

cc @lpetit-yseop

**Comment by abelsromero** [comment]
I have reproduced the issue with an invalid cross reference. @mojavelinux , is it normal that this error does not contain a cursor reference pointing to the document line?

**Comment by abelsromero** [comment]
fixed by https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/367

**Comment by abelsromero** [comment]
Will release in a 1.5.7.1 version with a possible jRuby update depending on this https://github.com/asciidoctor/asciidoctorj/issues/680

**Comment by mojavelinux** [comment]
> @mojavelinux , is it normal that this error does not contain a cursor reference pointing to the document line?

I may have already mentioned this somewhere else, but just in case, not all messages have a cursor (as we either don't have it or it's not relevant).
