### ISSUE TITLE
NPE with logHandler

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-maven-plugin#368]
I tried the new logHandler fail build feature in 1.5.7. When there is a warning, it fails with a NPE at
WARNUNG: Unexpected exception while logging Asciidoctor log entry
java.lang.NullPointerException
        at org.asciidoctor.maven.log.LogRecordHelper.format(LogRecordHelper.java:40)
        at org.asciidoctor.maven.log.MemoryLogHandler.log(MemoryLogHandler.java:34)

Everything is fine when I remove the warning. This does indeed fail the build, but I guess it is not intended like this. Do I need the loghandler library? I remember I have seen it in some test case or similar as an additional dependency, but I cannot find it again.

Let me know if I can be of any assistance for investigating this Exception.

**Comment by abelsromero** [comment]
Sorry for the issue, we are aware and `master` branch is already fixed.
We are also seeing a possible problem in asciidoctorj https://github.com/asciidoctor/asciidoctorj/issues/680.
If you need to fix this right now, you can build/install from master running `mvn install` and I also recommend increasing the version of jruby-complete to 9.1.17.0.

**Comment by eiswind** [comment]
Thanks a lot for letting me know!

**Comment by abelsromero** [comment]
v 1.5.7.1 with the fix has been released
