### ISSUE TITLE
Cannot set imagesDir to empty value when converting to DocBook 

### ISSUE THREAD

**Issue by mafritsch** [asciidoctor/asciidoctor-maven-plugin#378]
I want to use the asciidoctor-maven-plugin to convert AsciiDoc to DocBook. The path to images in the generated DocBook is always prepended with images/ which is the default value for the imagesDir parameter. 
It seems not to be possible to set the value to an empty string, so that no path is prepended to the images path. 

**Example:**
AsciiDoc:
`image::TestImage.png[scaledwidth='100%']`

DocBook:
`<imagedata fileref="images/TestImage.png" width="100%"/>`

Wanted result:
` <imagedata fileref="TestImage.png" width="100%"/>`

**Comment by abelsromero** [comment]
You can override the value to empty directly setting the attribute like this:

```xml
<attributes>
  <imagesdir/>
</attributes>
```

Btw, we are aware of the shortcoming and will change the default value for `imagesDir`
https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/296.

**Comment by mafritsch** [comment]
Thanks for the fast answer, that was what I was looking for.
