### ISSUE TITLE
Convert source code to DocBook example instead of formalpara

### ISSUE THREAD

**Issue by mafritsch** [asciidoctor/asciidoctor-maven-plugin#379]
The plugin converts source code with a title 

```xml
.Asciidoctor
[source, ruby]
----
My Code
----
```

into the following DocBook construct:

```xml
<formalpara>
 <title>AsciiDoctor</title>
 <para>
<programlisting>My Code</programlisting>
</para>
</formalpara>
```

Unfortunately, this DocBook code does not number the code examples. I expected to get something like:

```xml
<example>
  <title> Test title </title>
  <programlisting>My code</programlisting>
</example>
````

**Comment by abelsromero** [comment]
Sorry, my knowledge of docbook is limited, if you mean adding line numbers. You should be able to do so adding `linenums`:

```
.Asciidoctor
[source, ruby, linenums]
----
My Code
----
```
If that's not what you aim, I am afraid this should better be addressed to the core converter: https://github.com/asciidoctor/asciidoctor.

**Comment by abelsromero** [comment]
I am closing this issue given that (to my understanding at least) the main doubt was solved. If any other question remains, please feel free to file an issue to https://github.com/asciidoctor/asciidoctor.
