### ISSUE TITLE
Link attributes in links do not work 

### ISSUE THREAD

**Issue by mafritsch** [asciidoctor/asciidoctor-maven-plugin#381]
I am referring to the link macro described in asciidoctor documentation.

When I try to use this syntax, the extension does render the brackets content as if it were the entire text content:

link:view-source:asciidoctor.org[Asciidoctor homepage, window="_blank"]

Renders as:

![image](https://user-images.githubusercontent.com/530607/50168624-1fc43300-02ec-11e9-9456-bb1342e62469.png)

But window="_blank" should be an attribute of the link, not in the link text.

I have already added :linkattrs: to the header of my AsciiDoc document. I use the asciidoctor-maven-plugin to convert AsciiDoc to DocBook but the links is already wrong in the preview from the IDEA AsciiDoc plugin.

**Comment by mojavelinux** [comment]
Can you check which version of Asciidoctor you're using by entering:

```
{asciidoctor-version}
```

Also, make sure your doctitle uses the ATX heading style:

```
= Document Title
```

The `linkattrs` attribute should not be required when using Asciidoctor 1.5.7 or greater.

**Comment by mojavelinux** [comment]
> I replaced the heading in my document with your recommendation and the preview works now fine.

Yep, that was probably it. You were in compat mode, where linkattrs don't apply.

> However, the conversion to DocBook does not work as expected.

The built-in DocBook converter does not pass through arbitrary attributes, in this case xrefstyle. To my knowledge, xrefstyle doesn't apply to an arbitrary link (only an xref). If you intend just to pass it through as a role, then you should use the role attribute.

I'm happy to discuss further, though it doesn't pertain specifically to the Maven plugin.

**Comment by abelsromero** [comment]
I am closing this issue given the doubt was solved and this is not specific to the maven-plugin
