### ISSUE TITLE
Bibliography labels rendered incorrectly

### ISSUE THREAD

**Issue by Azer0s** [asciidoctor/asciidoctor-maven-plugin#383]
I have two entries in my bibliography that look like so:

```
- [[[turing1,10]]] Turing, A. M. (1936). link:https://www.cs.virginia.edu/~robins/Turing_Paper_1936.pdf[On Computable Numbers, With an Application to the Entscheidungsproblem]
- [[[goedel1,11]]] Gödel, K. (1931). link:http://www.w-k-essler.de/pdfs/goedel.pdf[Über formal unentscheidbare Sätze der Principia Mathematica und verwandter Systeme, I], Monatshefte für Mathematik und Physik, v. 38 n. 1, pp. 173–198.
```

I want them to be rendered like this:

* [10] Turing, A. M. (1936). [On Computable Numbers, With an Application to the Entscheidungsproblem](https://www.cs.virginia.edu/~robins/Turing_Paper_1936.pdf)
* [11] Gödel, K. (1931). [Über formal unentscheidbare Sätze der Principia Mathematica und verwandter Systeme, I](http://www.w-k-essler.de/pdfs/goedel.pdf), Monatshefte für Mathematik und Physik, v. 38 n. 1, pp. 173–198.

But instead they look like so:

* [turing1] Turing, A. M. (1936).  [On Computable Numbers, With an Application to the Entscheidungsproblem](https://www.cs.virginia.edu/~robins/Turing_Paper_1936.pdf) [https://www.cs.virginia.edu/~robins/
Turing_Paper_1936.pdf]
* [goedel1] Gödel, K. (1931). [Über formal unentscheidbare Sätze der Principia Mathematica und verwandter Systeme, I](http://www.w-k-essler.de/pdfs/goedel.pdf) [http://www.w-k-essler.de/pdfs/goedel.pdf],
Monatshefte für Mathematik und Physik, v. 38 n. 1, pp. 173–198

When referring to these sources I use `<<turing1>>` and  `<<goedel1>>`. Referring to these sources works and my labels are rendered correctly (as [10] and [11]). The IntelliJ asciidoc plugin also renders it correctly. But when I generate a PDF through maven, the label is rendered incorrectly.

<img src="https://i.imgur.com/FKajkL0.png"/>

**Comment by abelsromero** [comment]
This is a issue that affects `asciidoctor-pdf`, and not the HTML conversion, which is what IntellJ plugin does.

Good news, it's already fixed https://github.com/asciidoctor/asciidoctor-pdf/issues/864, but not released. I tested  monkey patched the gem locally and it works correctly with your [repo](https://github.com/Azer0s/languagedesign-paper).

You should ask @mojavelinux of this is planned to be released soon. In the meantime, you could consider 
https://github.com/asciidoctor/asciidoctor-bibtex or https://github.com/riboseinc/asciidoctor-bibliography. If you have issues setting the configuration, let me know and I can send you a PR.

**Comment by Azer0s** [comment]
Nice! Thanks for the quick response!

**Comment by abelsromero** [comment]
I am closing this issue, feel free to reopen if you need any other help with it

**Comment by mojavelinux** [comment]
I'll make sure a release of Asciidoctor PDF (1.5.0.alpha.17) goes out soon so it can be used with the plugin.
