### ISSUE TITLE
Upgrade to AsciidoctorJ 1.6.x, aligning with latest 1.5.x release of the Asciidoctor Gradle Plugin

### ISSUE THREAD

**Issue by wilkinsona** [asciidoctor/asciidoctor-maven-plugin#385]
The latest 1.5.x releases of the Asciidoctor Maven and Gradle plugins currently depend on AsciidoctorJ 1.5.x and 1.6.x respectively. Due to  breaking API changes in AsciidoctorJ 1.6, this makes it very hard for other projects in the Asciidoctor ecosystem to provide extensions that work with both Maven and Gradle when up-to-date plugin versions are used. Please see [this Spring REST Docs issue](https://github.com/spring-projects/spring-restdocs/issues/581#issuecomment-464676416) for an example of the problem that this causes.

I'm [aware](https://github.com/asciidoctor/asciidoctorj/issues/697) of the reasons for the breaking changes in 1.6, but I am still concerned about the Asciidoctor community being split between those stuck on 1.5 and those that can upgrade to 1.6. This concern has increased now that I understand that Maven and Gradle users are in different situations. Maven users who want to use the latest versions of their build system's plugin are forced to use AsciidoctorJ 1.5.x while Gradle users are forced to use AsciidoctorJ 1.6.x.

Given that the Gradle plugin team have decided to make the leap to AsciidoctorJ 1.6 in their latest 1.5.x release, could the Maven plugin please do the same? This would allow other projects in the ecosystem to make the move to AsciidoctorJ 1.6 and document the need to use the latest 1.5.x releases of the build plugin.

**Comment by bric3** [comment]
Before going to 2.0.0 (#391), can we at least have a 1.6.0 based released. I believe the 1.6.0 version of asciidoc was to enable a migration path to 2.0.0. I believe this would be a good first step, plus it'll help fix spring rest docs.

**Comment by mojavelinux** [comment]
What @wilkinsona is suggesting seems like a very fair and wise compromise to me.

**Comment by abelsromero** [comment]
You should be able to use v1.6.x with asciidoctor-maven-plugin 1.5.8, provided you update your extensions code to 1.6.x. I tested the code and the maven-examples repo against 1.6.x successfully.

**Comment by wilkinsona** [comment]
Thanks, @abelsromero. I didn't think to try the current Maven Plugin with an overridden version of AsciidoctorJ. It's good to know that works and is an option today.

FWIW, I still think it would be reasonable to publish a new release of the Maven plugin that uses AsciidoctorJ 1.6.x by default. That will align things with the Gradle plugin so that users have the same experience irrespective of their chosen build system.

**Comment by abelsromero** [comment]
> FWIW, I still think it would be reasonable to publish a new release of the Maven plugin that uses AsciidoctorJ 1.6.x by default. That will align things with the Gradle plugin so that users have the same experience irrespective of their chosen build system

We already did a 1.5.8 for that reason, so there's truly no reason for not doing so for 1.6.0. I'll try to get some time today.

> Thanks, @abelsromero. I didn't think to try the current Maven Plugin with an overridden version of AsciidoctorJ. It's good to know that works and is an option today.

Note that the gradle plugin also allows that using the `version` property in the `asciidoctorj` task (https://github.com/asciidoctor/asciidoctor-gradle-plugin#asciidoctorj-base-plugin).
I went through the documentation https://docs.spring.io/spring-restdocs/docs/2.0.3.RELEASE/reference/html5/ and I think it should be worth mentioning this. When you start adding converters and extensions setting a specific version helps a lot. Is it ok if I send a PR to master?

**Comment by abelsromero** [comment]
I just released a 1.6.0 version, should be available soon in maven central.
This contains all required changed for Asciidoctorj 1.6.2 usage, including Java minimal version is 8.

**Comment by bric3** [comment]
Great. Thanks a lot!
