### ISSUE TITLE
asciidoctor-maven-plugin fails on JDK 8u201 due to bouncycastle

### ISSUE THREAD

**Issue by bshannon** [asciidoctor/asciidoctor-maven-plugin#388]
Using plugin version 1.5.7 and trying to generate pdf output, it fails with:

`[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc (generate-pdf-doc) on project firstcup: Execution generate-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.7.1:process-asciidoc failed: (LoadError) load error: jopenssl/load -- java.lang.VerifyError: class org.bouncycastle.asn1.ASN1Primitive overrides final method equals.(Ljava/lang/Object;)Z -> [Help 1]
`

Using JDK 8u191 works.

I'm using asciidoctorj-pdf version 1.5.0-alpha.16.
The dependencies pull in jruby-complete version 9.1.17.0.

**Comment by mojavelinux** [comment]
You said that JDK 8u191 works. Could you clarify which JDK doesn't work? Thanks!

**Comment by mojavelinux** [comment]
Oops, my mistake. It's in the title.

**Comment by mojavelinux** [comment]
FYI the Travis build runs against openjdk version "1.8.0_141" (which is even older than the version you reported as working).

**Comment by mojavelinux** [comment]
Could you try to add the following to your JAVA_OPTS.

```
-Djruby.openssl.load.jars=false
```

That might tell us where the problem is coming from. Though I suspect this is a JRuby issue.

**Comment by bshannon** [comment]
Yes, that allows it to work.  Thanks!

Is there a way to set that in the pom.xml?

I suppose I should file a bug against jruby?

**Comment by mojavelinux** [comment]
Thanks for verifying!

> Is there a way to set that in the pom.xml?

Not sure. Perhaps @abelsromero knows.

> I suppose I should file a bug against jruby?

Perhaps. Though I first want to see if @abelsromero believe this might be an issue with the plugin adding jars to the classpath twice (or perhaps it's Maven). Once we confirm one way or the other, we can proceed with nagging JRuby.

**Comment by abelsromero** [comment]
I haven't been able to reproduce the issue in any of my available systems. I used the [pdf example](https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-example), and adding an include of an https resource with gitraw which in the past has triggered issues with bouncycastle....and nothing.

![image](https://user-images.githubusercontent.com/5781153/53680371-f73cba00-3cda-11e9-9537-67496a920e0c.png)

@bshannon first thing I'd recommend is upgrading to latest asciidoctorj (1.6.2) and jruby (9.2.6.0). Unless you are using some extension, this should be fine.
After that, and to decide this is whether a maven or jruby thing I need more info (OS, extension being used, maven version at least), or else if you can provide an example repo that would be perfect.


> Is there a way to set that in the pom.xml?

Not that I know of. Googling I see some plugins have options for that, but we don't have them, and honestly I think that setting environment variables in a configuration file goes against the idea of env vars.

**Comment by bshannon** [comment]
@abelsromero Upgrading the asciidoctorj and jruby versions didn't help.

I'll try to put together a reproducible example.  Right now it depends on a Maven plugin
that I'm in the middle of developing so I'll need to finish that or extract and rearrange
some things to create an example.

> I think that setting environment variables in a configuration file goes against the idea of env vars.

I wouldn't want to set environment variables or System properties in the asciidoctor-maven-plugin,
but I thought there might be a way to pass that setting just to jruby.

**Comment by bshannon** [comment]
I created a simple reproducible example.  Unfortunately, it only fails on Solaris.
I can't get it to fail on Linux.  I know jruby is doing something os-specific.
I tried to fake os.name, but that caused other failures.

I guess that means I need to file a bug against jruby.

**Comment by mojavelinux** [comment]
I agree, it looks that way. The good news is you're going in armed with
everything you need for a quick resolution, I'd say.

**Comment by bshannon** [comment]
I filed a [JRuby issue](https://github.com/jruby/jruby/issues/5640).

Thanks for your help.

**Comment by abelsromero** [comment]
> Thanks for your help.

I am glad we could find the case the issue at least.

**Comment by abelsromero** [comment]
Unrelated with Asciidoctor :point_right: solution in the linked jruby issue.
