### ISSUE TITLE
NullPointerException in LogRecordHelper

### ISSUE THREAD

**Issue by barthel** [asciidoctor/asciidoctor-maven-plugin#402]
* asciidoctorj: 1.6.2
* asciidoctor-maven-plugin: 1.6.0
* jruby-complete: 9.2.6.0
* asciidoctorj-pdf: 1.5.0-alpha.17

```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /usr/local/opt/maven@3.5/libexec
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"
```
```
Apr 25, 2019 1:52:13 PM org.asciidoctor.internal.JRubyAsciidoctor log
WARNING: Unexpected exception while logging Asciidoctor log entry
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at org.asciidoctor.maven.log.LogRecordHelper.format(LogRecordHelper.java:43)
	at org.asciidoctor.maven.log.MemoryLogHandler.log(MemoryLogHandler.java:34)
	at org.asciidoctor.internal.JRubyAsciidoctor.log(JRubyAsciidoctor.java:594)
	at org.asciidoctor.log.internal.JavaLogger.add(JavaLogger.java:90)
	at org.asciidoctor.log.internal.JavaLogger$INVOKER$i$0$2$add.call(JavaLogger$INVOKER$i$0$2$add.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:303)
[...]
```

This error is shown after I add a asciidoctor extension:
```
[...]
<dependency>
    <groupId>com.puravida.asciidoctor</groupId>
    <artifactId>asciidoctor-extensions</artifactId>
    <version>2.0.1</version>
</dependency>
[...]
```

**Comment by jagedn** [comment]
Can you try with the version `2.1.0` of `asciidoctor-extensions` I just released  ?

**Comment by barthel** [comment]
@jagedn thx for the new release.

The ```NullPointerException``` is fixed, **BUT** the ```LogRecordHelper``` should be more robust against.

**Comment by abelsromero** [comment]
> the `LogRecordHelper` should be more robust against.

I can try to see if there's something missing, but I would need a project to reproduce the issue. There are many varianles in place and without a concret case it's really hard to find what is causing the issue.

**Comment by jagedn** [comment]
Hi @abelsromero 

in this repo, branch maven, I have an example where the error happends

https://gitlab.com/puravida-asciidoctor/asciidoctor-amazon-template

I'm pretty sure is when I include the `asciidoctor-extensions` dependency but don't know why

**Comment by abelsromero** [comment]
Can you provide mode info about the environment and the error?
I see a different error than the one reported in this issue.

* Linux - OpenJDK8: project builds successfully 
* Linux - OpenJDK9, OpenJDK11 & Corretto11: the error below is shown in the console, but the build completes.

```
java.lang.NullPointerException
	at net.sourceforge.plantuml.math.AsciiMath.<init>(AsciiMath.java:83)
```

**Comment by abelsromero** [comment]
OK, forget the previous comment, I am not sure what happens. The reason the error is not shown is -I assume- some internal caching of some component. Running `mvn clean && mvn` always fails, running `mvn` twice makes the second time not to show any error.

But the formulas fail the same, and they also fail in the IntelliJ plugin with the same error.

**Comment by abelsromero** [comment]
Good news, comparing the gradle and maven build I see there's a missing dependency.

```xml
<dependency>
    <groupId>net.sourceforge.plantuml</groupId>
    <artifactId>plantuml</artifactId>
    <version>1.2019.5</version>
</dependency>
```

This fixes the build at least for Java8, Java 11 still fails. But the gradle plugin does work on Java11 but shows this message several times `Warning: Nashorn engine is planned to be removed from a future JDK release`.

**Comment by ysb33r** [comment]
> Warning: Nashorn engine is planned to be removed from a future JDK release.

Is this not a PlantUML issue instead?

**Comment by abelsromero** [comment]
Unable to reproduce, sorry. If someone can provide a reproducer, feel free to re-open.
