### ISSUE TITLE
asciidoctorj-pdf does not respect `preserveDirectories`

### ISSUE THREAD

**Issue by hupfdule** [asciidoctor/asciidoctor-maven-plugin#408]
I filed this issue against [asciidoctorj-pdf](https://github.com/asciidoctor/asciidoctorj-pdf/issues/19) first, but was told this is a problem with the maven plugin. Therefore I am copying this issue here now:

The asciidoctorj-option `preserveDirectories` is ignored by asciidoctorj-pdf.
I have a document with images that I want to convert to HTML and PDF with the following pom-snippet:

     <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>1.5.6</version>
        <dependencies>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>1.5.0-alpha.16</version>
          </dependency>
        </dependencies>
        <configuration>
          <sourceDirectory>${basedir}/src/doc/</sourceDirectory>
          <backend>xhtml5</backend>
          <sourceHighlighter>prettify</sourceHighlighter>
          <preserveDirectories>true</preserveDirectories>
          <attributes>
            <sectnums>true</sectnums>
            <toc>left</toc>
            <toclevels>3</toclevels>
            <imagesdir>.</imagesdir>
            <icons>font</icons>
          </attributes>
        </configuration>
        <executions>
          <execution>
            <id>manual-html</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>process-asciidoc</goal>
            </goals>
          </execution>
          <execution>
            <id>manual-pdf</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>process-asciidoc</goal>
            </goals>
            <configuration>
              <backend>pdf</backend>
              <sourceHighlighter>coderay</sourceHighlighter>
            </configuration>
          </execution>
        </executions>
      </plugin>

The document has the following structure:

     src/doc/                                                                                                                                                          
    └── my-manual
        ├── my-manual.adoc
        └── screenshots
            ├── screenshot1.png
            ├── screenshot2.png
            ├── screenshot3.png

When generating the PDF asciidoctorj-pdf tries to load the images from `src/doc/screenshots` even though I specified the `preserveDirectories` option that correctly behaves when generating the HTML output.

**Comment by mojavelinux** [comment]
This seems to me like a basedir issue. If Asciidoctor PDF is starting from "src" to look for images, then the basedir is the project. The basedir needs to either be unset, or set to the directory where my-manual.adoc is located. I don't think this has anything to do with preserveDirectories.

**Comment by abelsromero** [comment]
_Sorry for addressing this so late._

I am assuming images are indicated like this

```adoc
image::screenshots/screenshot1.png[]
```

In that case, what @mojavelinux says is right. 

Setting `sourceDirectory` to `${project.basedir}/src/doc/my-manual` fixes it.
Also, as an alternative you could keep `sourceDirectory`  as it is now now, remove `preserveDirectories` and set `relativeBaseDir` to `true`.
