### ISSUE TITLE
Warn/fail on broken internal references

### ISSUE THREAD

**Issue by elab** [asciidoctor/asciidoctor-maven-plugin#409]
How to warn/fail on broken internal references using asciidoctor-maven-plugin?

Setting `<enableVerbose>true</enableVerbose>` in plugin configuration has no effect.

Adding

    <logHandler>
        <outputToConsole>false</outputToConsole>
        <failIf>
            <severity>DEBUG</severity>
        </failIf>
    </logHandler>

doesn't help either. (The build succeeds without any messages despite of broken references.)

Plugin version: 2.0.0-RC.1

Example to reproduce:

    == ChapterA
    <<ChapterX>>

**Comment by abelsromero** [comment]
Internal references are a special case open in core https://github.com/asciidoctor/asciidoctor/issues/2722.
If you just want to see them in the console use `enableVerbose`, if you want to fail the build add this configuration to your pom

```xml
<logHandler>
    <failIf>
        <severity>INFO</severity>
    </failIf>
</logHandler>
```

**Comment by elab** [comment]
But I do all that (`enableVerbose`, `logHandler/failIf`) as you see above.
And don't see any messages in the build log.
Does it work for you?

**Comment by mojavelinux** [comment]
Could you share a snippet of the document you think you should be producing a message?

**Comment by elab** [comment]
Example:

    == ChapterA
    <<ChapterX>>

There is no message about non-existing target "ChapterX" in build log.

**Comment by mojavelinux** [comment]
The message we should expect to see is:

```
INFO: possible invalid reference: ChapterX
```

**Comment by elab** [comment]
But I don't see any such messages in my build log. (I'm using plugin v2.0.0-RC.1)
Does it work for you?

**Comment by mojavelinux** [comment]
I'm not saying it works. I'm clarifying the test case assertion.

**Comment by abelsromero** [comment]
I think I found the problem, the maven plugin by default runs on AsciidoctorJ-2.0.0-RC1. Try using the latest version as show here https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-html-example/pom.xml#L35

**Comment by elab** [comment]
It works now (with dependency of maven-plugin on asciidoctorj 2.0.0), thank you!

    [ERROR] asciidoctor: INFO: possible invalid reference: ChapterX
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------

as expected :)
