### ISSUE TITLE
Allow specifying OR / multiple failIf conditions

### ISSUE THREAD

**Issue by sherter** [asciidoctor/asciidoctor-maven-plugin#416]
I'd like to be able to fail the build if either severity is ERROR OR it contains some text, e.g.:

```
<enableVerbose>true</enableVerbose>
<logHandler>
  <failIf>
    <severity>ERROR</severity>
  </failIf>
  <failIf>
    <containsText>invalid reference:</containsText>
  </failIf>
</logHandler>
```

As far as I can tell, that is currently not possible but would be really useful.

**Comment by abelsromero** [comment]
We went that route to keep things simple and allow people to check very specific errors.
Why not use:
```xml
  <failIf>
    <severity>INFO</severity>
  </failIf>
```

**Comment by sherter** [comment]
Basically, I want to be able to fail on _some_ warnings (and all errors) but not all of them. E.g. I want to fail the build for invalid cross references, but I don't want to fail it for _"section title out of sequence_".
I know it would be best to just fix all errors, but sometimes that is just not feasible.

**Comment by abelsromero** [comment]
Apologies, I did not read correctly your example. I am afraid there's a confusion with the configuration, and probably the wording in the README does not help. You cannot set multiple `<failIf>` elements, it's a single block in which you can set `severity` and `containsText`, if both are set, the AND on both is applied.

On the topic of allowing different fail conditions, I tried something with a custom LogHandler injected using the SPI but it's not possible because exceptions are ignored by AsciidoctorJ (related with https://github.com/asciidoctor/asciidoctorj/issues/842).
I do think that the best approach would be to inject custom LogHandler to deal with this cases, but unless AsciidoctorJ behavior changes or Asciidoctor implements an event system there's not much to do.
The only alternative I see is creating an exclusive maven component that stores messages, users could extend it to programmatically decide what to do with them later.

**Comment by abelsromero** [comment]
After a test with a modification in AsciidoctorJ I could fail given your conditions with a custom LogHandler like this one.

```java
package org.asciidoctorj.example.loghandler;

import org.asciidoctor.log.LogHandler;
import org.asciidoctor.log.LogRecord;
import org.asciidoctor.log.Severity;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CustomLogHandler implements LogHandler {

    private static final Logger logger = LoggerFactory.getLogger(CustomLogHandler.class);

    @Override
    public void log(LogRecord logRecord) {

        if (logRecord.getSeverity().equals(Severity.ERROR)
                || logRecord.getMessage().contains("invalid reference:")) {
            final String msg = String.format("Critical issue found in %s %s: [%s] %s",
                    stripFilename(logRecord.getCursor().getFile()), logRecord.getCursor().getLineNumber(), logRecord.getSeverity(), logRecord.getMessage());
            logger.error(msg);
            throw new RuntimeException(msg);
        }
    }

    private String stripFilename(String filename) {
        return filename.substring(filename.lastIndexOf("/") + 1);
    }
}
```

To abort just throw any exception and you will get this as output:
```
[INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (asciidoctor-with-extension-example) @ asciidoctor-with-extension-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[ERROR] Critical issue found in example-manual.adoc 11: [ERROR] include file not found: /home/asalgadr/github/asciidoctor-maven-examples/java-extension-example/asciidoctor-with-extension-example/src/docs/asciidoc/connsasd.adoc
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Extension example aggregator 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Asciidoctorj twitter extension ..................... SUCCESS [  1.581 s]
[INFO] AsciiDoc to HTML with extension Maven Example ...... FAILURE [  4.928 s]
[INFO] Extension example aggregator ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.642 s
[INFO] Finished at: 2019-08-15T17:43:43+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (asciidoctor-with-extension-example) on project asciidoctor-with-extension-example: Execution asciidoctor-with-extension-example of goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc failed: asciidoctor: FAILED: /home/asalgadr/github/asciidoctor-maven-examples/java-extension-example/asciidoctor-with-extension-example/src/docs/asciidoc/example-manual.adoc: Failed to load AsciiDoc document: Critical issue found in example-manual.adoc 11: [ERROR] include file not found: /home/asalgadr/github/asciidoctor-maven-examples/java-extension-example/asciidoctor-with-extension-example/src/docs/asciidoc/connsasd.adoc -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :asciidoctor-with-extension-example
```

Messages to a `slf4j` logger will appear in the maven output as normal, and you can decide the level you prefer, in the example I used error. See the message beginning with "Critical issue found".

While this allows to apply any kind of rule, you need to code the LogHandler in a module and add it as a dependency to the plugin see https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/java-extension-example.

**Comment by sherter** [comment]
Thanks for providing this solution. I still think it would be cool if one could specify that directly in the pom in a more declarative fashion. But of course, if it's out of the scope of this maven plugin to provide such extended functionality, I can understand that you don't want to include it in the main project. Feel free to close the issue. Thanks again.

**Comment by abelsromero** [comment]
Thanks for you kind words.
Note that this to work depends on release of current `master` version of AsciidoctorJ. So I'll keep this open as traking.

Also, I reached the maven team with https://issues.apache.org/jira/browse/MNG-6734, it seems it would be possible in integrate code in the build more easily in the future. I think this approach offers much more options than adding all use cases to the plugin.
I'll chase that to see where it goes.

**Comment by abelsromero** [comment]
Closing. AsciidoctorJ integration is not possible.
