### ISSUE TITLE
Support warn for <attributeMissing>

### ISSUE THREAD

**Issue by wilkinsona** [asciidoctor/asciidoctor-maven-plugin#417]
The Asciidoctor user manual [recommends](https://asciidoctor.org/docs/user-manual/#missing-attribute) that `warn` is used for `attribute-missing`:

> leaves the reference intact, but also prints a warning about the missing attribute (recommended)

It doesn't appear to be possible to use it via the Maven plugin with `skip`, `drop`, or `drop-line` being the only supported values:

```
warn is not valid. Must be one of 'skip', 'drop' or 'drop-line'
```

https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/a4d86a949643ab68c124fd4c1b9b936412637d93/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L558-L562

Could support for `warn` please be added?

**Comment by wilkinsona** [comment]
As a workaround, it can be set via `<attributes>` instead:

```
<attributes>
	<attribute-missing>warn</attribute-missing>
</attributes>
```

**Comment by abelsromero** [comment]
I did not see that when reviewing changes for 2.0.0, and I am more in favor of using the attributes. How would you feel if we removed `attributeMissing` and `attributeUndefined` from <configuration>?

**Comment by wilkinsona** [comment]
That sounds good to me. I wasn't sure if `<attributeMissing>` would override whatever I'd configured in `<attributes>` so I was pleasantly surprised that the workaround was possible. Having only one way to configure it sounds good to me.

**Comment by abelsromero** [comment]
This configurations are legacies from early stages of the plugin in which we offered many attributes as configurations before fully supporting all `<attributes>`.

> I wasn't sure if `<attributeMissing>` would override whatever I'd configured in `<attributes>`

Attributes are applied after configurations, so they override any configuration.
