### ISSUE TITLE
torquebox proxy is not maintained and down, any workarounds?

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-maven-plugin#420]
https://github.com/torquebox/rubygems-servlets/issues/20

Are there any workarounds for using the rubygems with maven?

**Comment by abelsalgadoromeroWD** [comment]
Not yet, I followd the changes in gradle plugin and have been asking arround. But haven't found the time nor have a clear solution now.
If you have any insight or wanna try, discussion & PR are welcome.

**Comment by abelsromero** [comment]
Not yet, I followd the changes in gradle plugin and have been asking arround. But haven't found the time nor have a clear solution now.
If you have any insight or wanna try, discussion & PR are welcome.

**Comment by abelsalgadoromeroWD** [comment]
Thanks to @ysb33r who pointed me to check https://github.com/torquebox/mavengem/tree/master/mavengem-wagon

**Comment by eiswind** [comment]
I can approve that this works. Although the README is outdated, the latest version 1.0.3 did the trick.

**Comment by eiswind** [comment]
I created https://github.com/asciidoctor/asciidoctor-maven-examples/pull/92
for the examples.

**Comment by abelsromero** [comment]
Many, many thanks!
I will test it later.
