### ISSUE TITLE
feature request: support markdown as backend

### ISSUE THREAD

**Issue by ashakirin** [asciidoctor/asciidoctor-maven-plugin#424]
Hi,

I working a lot with asciidoctor maven plugin and find it really good in sense of quality and functionality.

The current use case is generations Rest API documentation using SpringBoot RestDocs. The SpringBoot RestDocs generates a snippets and asciidoctor plugin assembles them into template.

That works perfect for html, unfortunately Apigee requires markdown only documentation. SpringBoot Rest Docs already supports generation of markdown snippets, but I didn't find any maven plugin to assemble markdown snapshots into template.

Do you think it will be possible to support markdown backend in asciidoctor plugin and cover this use case?

The tricky part is that markdown doesn't has any "include" statement for the snapshots, it will be necessary to define own statement.

What do you think. If it make sense I am ready support implementation in any way.

Regards,
Andrei.

**Comment by abelsromero** [comment]
I am sorry, but this is not possible.
In terms of features, it's out of the scope to deal with other formats. Also, if I understand correctly, you need is to support includes in Markdown without conversion, which for me is a preprocessing task, not conversion on itself.
And in terms of solution, the maven plugin is only a front-end for the Asciidoctor libs. Markdown manipulation is something that has been discussed before and discarted.

As alternatives I can think of a few (given I have no idea of Apigee, so I can miss something):
* Directly publish HTML if it's possible
* Use some tool to convert from Asciidoc to Markdown -> here is a reference https://github.com/asciidoctor/asciidoctor/issues/1907, and googling you can find some more ways. Note that docbook is a backend supported out of the box. Find here an example https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/docbook-pipeline-docbkx-example.
* Implement yourself the Markdown manipulation, if you want to avoid the complexities of a maven-plugin you can use https://www.mojohaus.org/exec-maven-plugin/ to execute whatever language you feel more confortable with, even bash.

**Comment by ashakirin** [comment]
Hi Abel,

Thanks for you answer. Just curious what is the reason of completely discarding Markdown from Asciidoctor libs? Are there any chance for this to be revised in the future?

(a) HTML alternative is unfortunately not acceptable, because of Apigee restriction
(b) conversion through the Docbook is possible, but quite complicated 
(c) own Markdown manipulation seems the most realistic option at the moment

Regards,
Andrei.

**Comment by abelsromero** [comment]
I can't really say, the maven-plugin is a consumer tool of asciidoctor core libs, which is where this should be implemented. If you want to discuss this, better address the main repo (for instance here https://github.com/asciidoctor/asciidoctor/issues/1907) or in the forums https://discuss.asciidoctor.org/.

In the meantime, you can consider implementing a converter in either Ruby, Java (https://github.com/asciidoctor/asciidoctorj/blob/master/docs/integrator-guide.adoc#publish-everywhere-adapt-asciidoctor-to-your-own-target-format) or JavaScript (https://asciidoctor-docs.netlify.app/asciidoctor.js/extend/converter/custom-converter/). But this is no easy task.

**Comment by mojavelinux** [comment]
@ashakirin As @abelsromero points out, Asciidoctor is an AsciiDoc processor, not a Markdown processor. It's like asking for a screwdriver to be a hammer. These are just different things.

I'm not sure I understand what you mean by (a). This plugin can produce HTML from AsciiDoc. Why is that not acceptable?

If you want to writing in Markdown instead of AsciiDoc, I suggest looking for a plugin that converts Markdown.

**Comment by ashakirin** [comment]
@mojavelinux: 

> Asciidoctor is an AsciiDoc processor, not a Markdown processor. It's like asking for a screwdriver to be a hammer. These are just different things.

It is quite obvious that Asciidoctor is an AsciiDoc processor, I am asking about conversion from one document format to another. asciidoctor-maven-plugin currently provides a bunch of backend formats to convert into: html, pdf, docbook, epub, etc - why it is not acceptable to add markdown in this list?
I assume that PDF is different thing to AsciiDoc as well, anyway you don't consider it as screwdriver to be a hammer?

> I'm not sure I understand what you mean by (a). This plugin can produce HTML from AsciiDoc. Why is that not acceptable?


I am personally quite happy with generated HTML, but Apigee doesn't support it as documentation format on developer portal (https://cloud.google.com/apigee/api-management/developer-portal). I can redirect your question to Apigee guys, but I cannot change it. Currently I am restricted to use markdown only.

> If you want to writing in Markdown instead of AsciiDoc, I suggest looking for a plugin that converts Markdown.


I didn't find any plugin to include snippets produced by SpringBoot Rest Docs into main markdown document. Could you suggest any?

**Comment by mojavelinux** [comment]
>  html, pdf, docbook, epub, etc - why it is not acceptable to add markdown in this list?

I'm sorry I misunderstood you. Now I get that you are asking about *producing* Markdown rather than *converting* markdown. :facepalm:

I agree that would be a nice thing to have. While there isn't a converter focused solely on classic Markdown, there is a converter to convert to leanpub-flavored Markdown. That converter can also convert to classic Markdown (though it's not documented as a target backend). See https://github.com/asciidoctor/asciidoctor-leanpub-converter

If you add that converter to the plugin classpath, then you can select it as a target format.

**Comment by mojavelinux** [comment]
(I got confused when you said "include"). But if I read your original report, I see that you asked about "backend". Again, sorry for missing that.

**Comment by ashakirin** [comment]
Yeah, perhaps I described it not clear enough in the first post, thanks for your support!
Do you think it will be possible to add "feature request" for the Asciidoc / asciidoc-maven-plugin project? How the process normally look like?

**Comment by mojavelinux** [comment]
> perhaps I described it not clear enough in the first post

This one was my fault.

> Do you think it will be possible to add "feature request" for the Asciidoc / asciidoc-maven-plugin project

A change shouldn't be required to the code to support the asciidoctor-leanpub-converter, though an example would certainly be helpful. @abelsromero have you ever tried to load that converter into the Maven plugin?

**Comment by abelsromero** [comment]
> @abelsromero have you ever tried to load that converter into the Maven plugin?

Just did and is not yet compatible with the latest version of Asciidoctorj
https://github.com/asciidoctor/asciidoctor-leanpub-converter/issues/83. But that's easy to fix.

However, for the sake of managing expectations :point_up:  not all Asciidoctor features are supported in the Markdown converter based on some test I did with a direct AsciidoctorJ integration.

**Comment by ashakirin** [comment]
Thanks a lot to you guys, for cooperation!

**Comment by abelsromero** [comment]
Just for reporting. I did some testing back in the day and the asciidoctor-leanpub-converter just covers very especifc usecases required for leanpub. Imo is far from general use and would require some serious work.
I'd suggest that if this is necessary a separated Markdown converter to be done, plus it would be free to support any MD flavor without relation with leanpub. Since this is not a thing in the plugin scope I'll cose this issue.
If such converter is done, it can be integrated with the SPI.
