### ISSUE TITLE
WARNING An illegal reflective access operation has occurred (JDK11)

### ISSUE THREAD

**Issue by khmarbaise** [asciidoctor/asciidoctor-maven-plugin#425]
I'm currently running asciidoctor-maven-plugin:2.0.0-RC1 which unfortunately produces the following WARNINGs.
```
[INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (output-html) @ itf-documentation ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper (file:/Users/xxxx/.m2/repository/org/jruby/jruby-core/9.2.6.0/jruby-core-9.2.6.0.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
````

My environment:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/xxx/tools/maven
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Users/khmarbaise/tools/jdk-11.0.7+10/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

BTW: Is 2.0.0* maintained in that repo cause I don't see a branch for 2.0.0 ? Nor a release on the github page?

**Comment by abelsromero** [comment]
> I'm currently running asciidoctor-maven-plugin:2.0.0-RC1 which unfortunately produces the following WARNINGs.

This do not affect functionality but to clarify I asked help from jRuby team to see it https://github.com/jruby/jruby/issues/6189. In their repo they have other similar issues and in some cases it was not normal to see it.

> BTW: Is 2.0.0* maintained in that repo cause I don't see a branch for 2.0.0 ? Nor a release on the github page?

Apologies, `master` branch is the development one. Given the RC is compatible with old and recent versions of Asciidoctorj, and personal stuff haven't been able/not seen urgent to produce the final release.
Also, since asciidoctor & asciidoctorj 2.x introduced heavy non-compatible changes and we promote always running on the most recent versions, I did not deem worthy to keep a branch. In case of urgent hot fix tags are available.

**Comment by khmarbaise** [comment]
Hi, no apologies needed. Ok..`master` is the truth...take your time ...I know how it is working on open source...I was just a little bit confused not seeing the RC1 on the https://github.com/asciidoctor/asciidoctor-maven-plugin/releases page. 
Thanks for your fast answer and your work in the maven plugin.  
I know  that the functionality is not a problem with the warning..it will only trigger some hint in my CI ..that's all.

**Comment by abelsromero** [comment]
I am checking and I see it, below 1.6.0

**Comment by khmarbaise** [comment]
Outch ... Thanks...

**Comment by abelsromero** [comment]
Finally, about the warning messages, this are intrinsic and definetly nothing to worry, if you want to remove them just run with the following flags `--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/javax.crypto=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED`. I added them via `MAVEN_OPTS` and this worked.

**Comment by famod** [comment]
@abelsromero I guess the proper fix would be to upgrade to jRuby 9.3.0.0 once it is released? Shall I create a ticket for that?

**Comment by abelsromero** [comment]
I am curious but also odd question @famod have you by change tested against jruby snapshot? I can give it a try later or tomorrow

**Comment by famod** [comment]
@abelsromero Sorry, I have not tested against a jruby snapshot.

**Comment by abelsromero** [comment]
:smile: don't worry, totally normal. If we can confirm this really fixed the issue, we can just reopen this issue and mark as tracking + report to the Asciidoctorj team also.

**Comment by abelsromero** [comment]
I just tested `9.2.12.0` and the messages no longer appear. Asciidoctorj has already made the change in the development branch.
