### ISSUE TITLE
Rouge Highlighting is not working in 2.0.0

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-maven-plugin#444]
After upgrading from RC01 to 2.0.0 I see that my custom rouge style does not get applied anymore.

```
<execution>
    <id>generate-slides</id>
    <phase>process-resources</phase>
    <goals>
        <goal>process-asciidoc</goal>
    </goals>
    <configuration>
        <requires>
            <require>${project.build.directory}/out/rouge/custom.rb</require>
        </requires>
        <sourceDocumentName>${source.document}.adoc</sourceDocumentName>
        <outputDirectory>${project.slides.directory}</outputDirectory>
        <outputFile>${project.slides.directory}/${source.document}.html</outputFile>
        <backend>revealjs</backend>
        <sourceHighlighter>rouge</sourceHighlighter>
        <attributes>
            <rouge-css>style</rouge-css>
            <rouge-style>custom</rouge-style>
            <project-version>${project.version}</project-version>
            <customcss>assets/custom.css</customcss>
        </attributes>
    </configuration>
</execution>
```

Do I need any changes in my config?

**Comment by abelsromero** [comment]
Some options have been moved, refer to the migration guide: https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/docs/v2-migration-guide.adoc.

I'll add a note in the main README to make it more visible.

**Comment by abelsromero** [comment]
Btw, if you are building slides with reveal, you may need to set the jruby version explicitely to 9.2.9.0. Check the example https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-revealjs-example/pom.xml.

**Comment by eiswind** [comment]
Thanks for helping me out with that!
