### ISSUE TITLE
include an adoc file form a different svn maven project

### ISSUE THREAD

**Issue by smt-mj** [asciidoctor/asciidoctor-maven-plugin#490]
Hi,

we want to have multiple svn maven projects (one per big chapter). 
so we can aggregate whatever chapters we need in another "aggegation" project, containing adoc, which will only have adocs with includes.

1.  is this possible? if yes, how to include (dependecie in pom?, include path definition?)
2.  if its possible, will the aggregation adoc need to render evey include again on build time? (even if the other chapter projects already have been build?

thanks, best regards,
Mario

**Comment by abelsromero** [comment]
I explored it a bit more and may be more viable than what I initially though. I build a full example and found the `reader` provides the information required for relative includes, so what I sai before is not true.

This is not an endorsement, but I think this could help you explore the options and and decide for yourself. 
https://github.com/abelsromero/asciidoctorj-maven-includeprocessor

**Comment by smt-mj** [comment]
thanks for the clarification and the help. i must explore further, that if the possibility with this point of images is working out.
