### ISSUE TITLE
Running an extension without generating output?

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-maven-plugin#494]
I create multiple outputs for my adocs: revealjs, pdf and plain html.
Before running these, I need all docs to go through a preprocessing extension. How can I run this extension with the Maven plugin? At the moment I attach the extension to each of the three processing output goals, but that would be more logical and quicker to have it running before. Thx!

**Comment by abelsromero** [comment]
If I understand correctly, the question is if it's possible to run the extension once and then generate the different outpus?
If thats it, I am sorry to say that's not possible. Each conversion is run independently, that includes parsing, conversion + extensions. Not even the underlying Asciidoctor core components allows defining multiple output formats (backends).

You should be able to avoid duplicate configurations using `<extensions>` in the general `<configuration>` section or defining an SPI file in the plugin jar. But it will still run on every exectution.

Are you noting some specific performance issue?

**Comment by seinecle** [comment]
Thx! It is just that the pre processing by the extension needs to be done once: it converts sources into "intermediary source files", downloads some pics, checks some syntax stuff... This step needs to be performed just once, then these intermediary source files serve as inputs to the executions to generate html, pdf and slides.

I solved my problem by creating an extra execution running before the others: it contains only the extension. Besides generating my "intermediary source files" and doing what I need, it should create output files (html by default I think, right?), but I didn't locate these output files on my disk (?), so not sure how / where they went. I don't need them anyway.

**Comment by abelsromero** [comment]
> I solved my problem by creating an extra execution running before the others: it contains only the extension.

That's the best way I can think of :+1: 


> Besides generating my "intermediary source files" and doing what I need, it should create output files (html by default I think, right?)

It should, unless the extension is messing. Is is a public repo I can have a look at?

**Comment by seinecle** [comment]
Yes that's the pom of the project: https://github.com/seinecle/gephi-tutorials/blob/master/pom.xml

And that's the folder with my extensions: 
https://github.com/seinecle/asciidoctorj-extensions-custom/tree/master/asciidoctorj-extensions/src/main/java/net/clementlevallois/asciidoc/extensions

**Comment by abelsromero** [comment]
I had to do some changes to be able to build locally because there are some external dependencies, but I got to run the goal with the extension.
In my machine, the `CommonPreProcessor` creates the new files in `/src/main/asciidoc/subdir` and then generates the html in `target/generated-docs` as expected. I checked and there's a way to avoid generation but the plugin does not support it, there's a "load" method on the API.

Said that, I must admit I don't think this a good approach for the problem. I see the convenience, but at the end, all the logic of the extension could be done in a normal java process that parses the files, no real need for the plugin+AsciidoctorJ overhead.
The only feature the plugin and extension provide here is traversing and supling a reader for each source file.
I think a simple main method could to the same:
- could be invoked with `exec-maven-plugin-
- Use https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/GlobDirectoryWalker.java to find sources in a specific path
- Use `https://github.com/asciidoctor/asciidoctorj/blob/8793c1f8308893339090ded28af386c8972a4dba/asciidoctorj-api/src/main/java/org/asciidoctor/Asciidoctor.java#L512` load to just parse it. Or inject an empty custom empty converter.

**Comment by abelsromero** [comment]
I brought up the topic in the gitter channel and someone else commeted that fact that the goal here is to fetch remote content. So maybe having the sources pointing to local resources and just having a process downloading them based on path conventions could be an option. If all images are under the same path could be easy to have an attribute with the path so you can point to a remote resource or a local one.

**Comment by djencks** [comment]
That was me :-)  I think your approach is likely to work and it may be good for your situation, time you want to spend, etc, but... I think I would divide up the problem and consider where the best place to solve each part is.
IIUC, you have some asciidoc documents that refer to remote images and you want to:
- fetch the remote images to a local location
- process the documents into several output formats
- have each output format refer to the local copy of the image.

There's some infrastructure here:
- What determines, sets up and maintains the location for the local copies of the images?
For example, in an Antora build, this would be the build/site/.../_images directory for a module that Antora constructs on each build.
- Do you want local caching as well?
For example, using Antora, there's a lot of caching of remote content.

Trying to deal with this level of infrastructure in an asciidoctor extension is going to be a bad fit.  It should go into the code that runs asciidoctor. It's possible that all of this can be squeezed into the maven configuration :-)

The most natural way to recognize images to download at the moment is in the converter, with the convert_image and convert_inline_image calls.  At least for an html converter, I believe you can intercept these with one or two templates. (Antora is stuck on asciidoctor 1.5.9 at the moment so I don't have any personal experience with templates: Antora extends the build-in converter to intercept these convert_ calls and rewrite the output).  Your implementation of these methods can initiate download of the images if necessary and rewrite whatever is necessary to refer to the local-copy location of the image.

In the future I hope that it will be possible to replace the built-in implementations of the image: and image:: "macros" with implementations from an extension, but that is an idea that AFAIK hasn't been seriously discussed.

**Comment by abelsromero** [comment]
Closing, I understand the questions is solved. If there's any one questions, do no hesitate to open a new issue.
