### ISSUE TITLE
Multiple outputs, but copying resources just once?

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-maven-plugin#495]
[Question]
My project outputs sources in multiple formats (html, revealjs, pdf). Is it possible to have the step of copying resources triggered just once? As far as I see in the doc, each execution of the plugin triggers the copying of the resource, and I'd like to have it happen just once. Thx!

**Comment by abelsromero** [comment]
"executions" are a maven feature to allow multiple executions of plugin goal independently, there's nothing we can do to run _sub-tasks_ like the copy of resources independently.

If you need to modify the build, the maven way is to setup a plugin to do the job in a different phase.
The way I can think of is:

1. Configure the [resource plugin](https://maven.apache.org/plugins/maven-resources-plugin/) to run AFTER the asciidoctor plugin and copy the resources to the target path.
2. Configure the asciidoctor plugin to exclude all resources so nothing is copied. This should work:

  ```xml
  <resources>
      <resource>
          <directory>.</directory>
          <excludes>
              <exclude>**/**</exclude>
          </excludes>
  </resources>
  ```

**Comment by seinecle** [comment]
Thx!

**Comment by abelsromero** [comment]
Closing, I understand the questions is solved. If there's any one questions, do no hesitate to open a new issue.
