### ISSUE TITLE
define all maven properties as attributes

### ISSUE THREAD

**Issue by sekaijin** [asciidoctor/asciidoctor-maven-plugin#505]
https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/489

**Comment by abelsromero** [comment]
> I just did some tests and contrary to what is said in the answer, this functionality is not present.

The feature is working as intended, but maybe we can improve the docs.
The plugin injects the properties defined in the `<properties>` section of the project, not the "Maven Project Properties" (see 9.2.1 https://books.sonatype.com/mvnref-book/reference/resource-filtering-sect-properties.html).

I tested and:

* This is replaced in the doc as expected.
  ```xml
  <properties> <my.sample.property>foo value</my.sample.property> ... </properties>
  ```
* This is not replaced, also as expected, unless you add it explicitly as attribute or property.
  ```
  version: {project-version}
  ```
