### ISSUE TITLE
define all maven properties as attributes

### ISSUE THREAD

**Issue by sekaijin** [asciidoctor/asciidoctor-maven-plugin#506]
Hi

I reopen this ticket : #489
I just did some tests and contrary to what is said in the answer, this functionality is not present.

The ticket proposes to automatically add all the maven properties in the list of attributes.
However, the answer proposes to add manually, one by one, each property as an attribute.

```
<properties>
    <my.sample.property>foo value</my.sample.property>
    ... 
</properties>
```

```
<configuration>
  <sourceDirectory>src/docs/asciidoc</sourceDirectory> 
  <outputDirectory>target/docs/asciidoc</outputDirectory> 
  <backend>html</backend> 
  <doctype>book</doctype> 
  <!-- just set true and this define an attribute for each property --> 
  <propertiesAsAttributes>true</propertiesAsAttributes> 
  <attributes> 
    <stylesheet>my-theme.css</stylesheet>
  </attributes> 
</configuration>

```
in foo.adoc

```
== Sample

This project does something.
version: {project-version}
property value: {my-sample-property}
```

where the answer suggests doing:

```
<configuration> 
   <sourceDirectory>src/docs/asciidoc</sourceDirectory> 
   <outputDirectory>target/docs/asciidoc</outputDirectory> 
   <backend>html</backend> 
   <doctype>book</doctype> 
   <attributes>
      <stylesheet>my-theme.css</stylesheet> 
      <my-sample-property>${my.sample.property}</my-sample-property> 
      <project-version>${project.version}</project-version> 
      <!-- each time for each property --> 
      ... 
   </attributes> 
</configuration>
```

Bye

**Comment by sekaijin** [comment]
Ho!

It's more subtle than I thought.
`my.sample.property` is a property because it is defined in` <propeties> `, but` project.version` is defined in the maven model so it is not a property.
In maven `$ {foo}` refers indefinitely to a property or an attribute of the model. We therefore use `$ {my.sample.property}` in the same way as `$ {project.version}`.
The asciidoctor plugin makes a difference. We can use `{my-sample-property}` because the `my.sample.property` property is imported automatically. But model attributes, like `project.version`, are not. It is therefore necessary to add it to the list of `<attributes>`.

I think the documentation should be more specific on this.
With these details I think we can close.

**Comment by abelsromero** [comment]
Improved the docs https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/507. See anything can be improved?
Note I am trying to keep it short.

**Comment by sekaijin** [comment]
thank for all
