### ISSUE TITLE
Remove usage of internal Asciidoctorj DirectoryWalker

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#532]
**What is this issue about?**

- [ ] Bug report
- [ ] Feature request
- [ ] Question
- [x] Refactor/Improvement

**Description**
Currently, we use `org.asciidoctor.jruby.AsciiDocDirectoryWalker` and `org.asciidoctor.jruby.DirectoryWalker` to obtain AsciiDoc sources from the paths. But his classes are not part of the asciidoctorj-api but the jruby implementation, this breaks encapsulation and prevents the plugin from working with other AsciidoctorJ implementations using the service loader.
We should replace this by some agnostic piece with same functionality, for example [FileUtils.listFiles](http://commons.apache.org/proper/commons-io/apidocs/index.html?org/apache/commons/io/FileUtils.html).

Reference: https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/2a79b16fda4ad30f78ff86799dfd9ecac7cc832f/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java#L439-L450

PD: there are other jruby specifics being used, but we can treat them in another issue.

**Comment by abelsromero** [comment]
Since this is internal change, there should be no need for new tests.

**Comment by stdll** [comment]
Hi! Sorry for spamming this issue. I've looked into the issue and came up with a PR. If you have feedback, please let me know.

**Comment by abelsromero** [comment]
> Hi! Sorry for spamming this issue.

No problem 👍 My only suggestion is if you have a long running PR, just mark as "Draft" so people is aware is not finished. But even that's opinionated and some ppl prefer not getting the PR untill is finished 🤷 

I can't promise I can look into the issue today, but I'll try.
