### ISSUE TITLE
Clearly document usage of internal files

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#548]
Thank you for taking your time to talk with us!

**What is this issue about?**

- [ ] Bug report
- [ ] Feature request
- [ ] Question
- [x] Documentation

**Description**
Usage of internal files (prefixed with _) can be better exposed in the docs.
Current explanation in a simple admonition that can pass unnoticed. As suggested in https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/545#issuecomment-886172252 it's much better if have an specific section. 
```
That means either putting this information in the preamble, or a section above "Setup" 
named "How files are processed". There, it can say that this plugin looks for all AsciiDoc 
files in the specified directory, but ignores files that are considered non-public, such
 as internal include files and hidden files.
```
This section can be set in a partial file to be reused for all goals.

For clarification: current behaviour was inherited from AsciidoctorJ https://github.com/asciidoctor/asciidoctorj/blob/main/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/AsciiDocDirectoryWalker.java.

**Comment by abelsromero** [comment]
Another thing to add is to also document and test that files with "." prefix are also not processed.

**Comment by abelsromero** [comment]
Replaced by https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/549

**Comment by mojavelinux** [comment]
Oops. I didn't realize you had filed an issue too. Sorry for not checking first.
