### ISSUE TITLE
Encoding Windows-1250 is used when trying to compile with pdf-stylesdir

### ISSUE THREAD

**Issue by miroslav-beranic** [asciidoctor/asciidoctor-maven-plugin#559]
- [x] Bug report
- [ ] Feature request
- [ ] Question

**Description**

**Environment information**

* asciidoctor-maven-plugin version: 2.2.1 ( also 2.1.0 )
* asciidoctorj version: 2.5.2 ( also 2.4.1 )
* Maven, Java and OS version: Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/miroslav/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5284.40/plugins/maven/lib/maven3
Java version: 1.8.0_282, vendor: AdoptOpenJDK, runtime: /opt/jdk8u282-b08-hotspot/jre
Default locale: sl_SI, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-37-generic", arch: "amd64", family: "unix"

In my pom.xml:

```
<plugin>
    <!--
    https://docs.asciidoctor.org/maven-tools/latest/plugin/goals/process-asciidoc/
    -->
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>${asciidoctor.maven.plugin.version}</version>
    <dependencies>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-pdf</artifactId>
            <version>${asciidoctorj.pdf.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jruby</groupId>
            <artifactId>jruby-complete</artifactId>
            <version>${jruby.version}</version>
        </dependency>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>${asciidoctorj.version}</version>
        </dependency>
    </dependencies>
    <executions>
        <execution>
            <id>generate-pdf-doc</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>pdf</backend>
                <enableVerbose>true</enableVerbose>
                <encoding>${project.build.sourceEncoding}</encoding>
                <!--
                <attributes>
                    <pdf-stylesdir>${project.basedir}/src/docs/theme</pdf-stylesdir>
                    <pdf-style>custom</pdf-style>
                </attributes>
                -->
            </configuration>
        </execution>
    </executions>
</plugin>
```

When using like this, source document.adoc is using `utf-8`, but when I un-comment `pdf-stylesdir` and `pdf-style`, source is read as `windows-1250` and I get corrupted PDF output and a lot of warning in console while build time.

Maven build output:
```
...
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ project ---
[INFO] Deleting /path/to/target
[INFO] 
[INFO] --- asciidoctor-maven-plugin:2.2.1:process-asciidoc (generate-pdf-doc) @ project ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] asciidoctor: WARN: The following text could not be fully converted to the Windows-1252 character set:
| Miroslav Beranič
...
```

**Comment by mojavelinux** [comment]
You're being misled by the warning message. The message "The following text could not be fully converted to the Windows-1252 character set" does not mean the document is being encoded in Windows-1252. What it means is that you're theme is using an AFM font, which does not support characters outset the Windows-1252 charset (in this case, č). In other words, you need to be using a TTF font instead.

Please refer to this page in the docs: https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.6.x/docs/theming-guide.adoc#built-in-afm-fonts

**Comment by miroslav-beranic** [comment]
I managed to make it work. In general guide is correct, but it is not as "easy" and "start&go" experience as it was to start with Asciidocs. I guess 99% of users that will use AsciiDocs to produce PDF ( mostly developers documenting source code ) will have to go over the same. I can not find Github repo now, where I started off from, but I am quite sure in that examples folder this was not obvious. Pre-bundled example in github repo would be perfect -- just to kickstart. Once initial investigation is possitive team will be more interested in reading all the documentation on how to customize it.

To me, this solved it, I started with Roboto font, but --- I need some head scratches to figure all out.

**Comment by mojavelinux** [comment]
Aha! This theme should extend from the default theme.

https://github.com/asciidoctor/asciidoctor-maven-examples/blob/main/asciidoctor-pdf-with-theme-example/src/theme/custom-theme.yml

Creating a theme from scratch it much, much harder and I don't think we should be encouraging it in that example. Abel, do you want me to file a separate issue for that?
