### ISSUE TITLE
[Security] Workflow build.yaml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by igibek** [asciidoctor/asciidoctor-maven-plugin#562]
The workflow build.yaml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by abelsromero** [comment]
Unless I am missing something we already use [v2](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/7a0c6f83c98142fa0ba0e1af419ecd754a4ed10c/.github/workflows/build.yaml#L27). If I am mistaken, please feel free to re-open with further details.
