### ISSUE TITLE
New release for maven site 4.x.x ? 

### ISSUE THREAD

**Issue by hgschmie** [asciidoctor/asciidoctor-maven-plugin#589]
**What is this issue about?**

- [ ] Bug report
- [ ] Feature request
- [X] Question

**Description**

Can we get a release that is compatible with the maven site 4.x.x plugin? I am running into the (known) issue with generating site docs with the latest site plugin and it seems that this is fixed in master but not yet released.

**Comment by abelsromero** [comment]
We could do a `3.0.0-RC1` release on Monday.

**Comment by michael-o** [comment]
I currently don't recommend upgrading because it is still in flux. I guess somewhere around fall I will have something usage. Until then, spare your time. Doxia 2.0.0 stack GA won't be available before winter.

**Comment by abelsromero** [comment]
That's why I was thinking about a "Release Candidate" in a "use at your own risk". But I am aware this can be confusing for users and even create a bad impression if APIs change, @michael-o do you now recommend it then? I greatly value your suggestions here.

**Comment by michael-o** [comment]
> That's why I was thinking about a "Release Candidate" in a "use at your own risk". But I am aware this can be confusing for users and even create a bad impression if APIs change, @michael-o do you now recommend it then? I greatly value your suggestions here.

I would wait at least next Doxia Core milestone. It will contain some important changes. I'd stay put until that, then we can resume the discussion.

**Comment by abelsromero** [comment]
Thanks a lot, we will wait then.

**Comment by abelsromero** [comment]
Given the timeframe and to avoid this blocking any possible release I think the best is to revert the changes from the main branch and maintain them in another, so:
* Will create a branch `issue-578-experimental-maven-site-4.x.x` with current changes.
* Reopen issue https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/578 to keep track of changes.
* Will remove commits https://github.com/asciidoctor/asciidoctor-maven-plugin/commit/f76071af094dad3eb5badee73b3d2138e20cba8b, https://github.com/asciidoctor/asciidoctor-maven-plugin/commit/4d82faaece02417833f0d8232e0ffc5034bbc98c from `main`. This will require a rebase from main directly on the repo.

**Comment by abelsromero** [comment]
Changes have been committed, any action/question regarding maven-site v4.x should be addressed in https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/578.

Thank you all!
