### ISSUE TITLE
Create an AsciidoctorWarMojo to generate a war file with rendered documentation

### ISSUE THREAD

**Issue by lordofthejars** [asciidoctor/asciidoctor-maven-plugin#59]
I have seen that in Asciidoctor-Maven-Plugin you can render the AsciiDoc files to the required output (let's say html5) and then zip it or for example make them available as an http resource using Netty. 

But I think could be also useful to generate a `war` file ready to be deployed in an application server like Tomee, JBoss, ... using for example Cargo plugin or any Jenkins plugin.

I am thinking about a scenario that happens in my case. We are using a farm of jenkins to generate our software versions which if compiles, all tests passes, ... they are deployed into a test environment. But if we were using AsciiDoc and Maven plugin to render all the documentation, all these documentation would be generated into a directory which on next build job would be removed, so it would not be available to external departments. One solution could be generating a zip file and copy it to a shared directory, but also if a `war` was generated then we could automatically deploy it to a documentation server.

**Comment by abelsromero** [comment]
I am closing this as "won't fix". This can be acomplished in combination with other plugins and I want to keep the plugin simple.
Furthermore the zip mojo is deprecated.
