### ISSUE TITLE
[Q] How to generate multiple files from single repository with sources in subfolders?

### ISSUE THREAD

**Issue by marceloverdijk** [asciidoctor/asciidoctor-maven-plugin#611]
Thank you for taking your time to talk with us!

**What is this issue about?**

- [ ] Bug report
- [ ] Feature request
- [X] Question

**Description**

I'm wondering if the Maven plugin can help me with this setup and what I'm trying to accomplish.

I have this project structure:

```
src
`-- docs
    `-- asciidoc
        |-- doc1
        |   |-- index.adoc
        |   `-- includes_for_doc1
        |       |-- include1.adoc
        |       `-- include2.adoc
        |-- doc2
        |   `-- includes_for_doc2
        |       |-- include1.adoc
        |       |-- include2.adoc
        |       `-- include3.adoc
        |-- doc3
        |   |-- index.adoc
        |   `-- includes_for_doc3
        |-- nested1
        |   |-- nested1doc1
        |   |   |-- index.adoc
        |   |   `-- includes_for_nested1doc1
        |   `-- nested1doc2
        |       |-- index.adoc
        |       `-- includes_for_nested1doc2
        `-- nested2
            |-- nested2doc1
            |   |-- index.adoc
            |   `-- includes_for_nested2doc1
            `-- nested2doc2
                |-- index.adoc
                `-- includes_for_nested2doc2
```

In this case I want to generate (both html and pdf) for the following files:"

- doc1.pdf
- doc2.pdf
- doc3.pdf
- nested1doc1.pdf
- nested1doc2.pdf
- nested2doc1.pdf
- nested1doc2.pdf

I could create separate execution configs for each file but this will be very cumbersome as I have quite some files.

Is there some smart way to do this?

**Environment information**

* asciidoctor-maven-plugin version: 2.2.2
* asciidoctorj version: 2.5.7

**Comment by abelsromero** [comment]
From top of my head, you can play with different options so the plugin identifies only the "index" files. But still you won't be able to customize the output name, use  `preserveDirectories` so at least they are generated in different folders.
* `sourceDirectory`: place them all in the same directory. Downside, you'll need to name them differently or create something like `index/doc1/index.adoc`, `index/doc2/index.adoc`, ... set it to `${basedir}/src/main/asciidoc/index` and enable `preserveDirectories`.
* `[sourceDocumentExtensions](https://docs.asciidoctor.org/maven-tools/latest/plugin/goals/process-asciidoc/#sourceDocumentExtensions)`: you can use a different file extension, ad, adoc and asciidoc are searched by default but you could narrow it down to one. For instance use adoc for index, and ad for included content.

Another option is to script it calling Maven multiple times from bash setting source/target https://docs.asciidoctor.org/maven-tools/latest/plugin/command-line-configuration/.


Finally, just in case you don't know, executions inhering configuration from the general configuration section. You would only need to replace the source and target name if you place all the rest together inside <configuration>. Still there's a lot of xml verbosity, but you can reduce the configuration to minimum required and keep things easy to understand.
Executions (or sub-modules) is the way Maven is design to work for this use cases, anything else is a hack.

btw, is there any constrain in the how the output should be placed? By default all docs will end up in the same directory.

**Comment by marceloverdijk** [comment]
Thx @abelsromero I will find a way to organize it best. I can easily change the "index" to an actual name of the file.

Another I noticed when generating pdf output , is that it copies all resources although embedded in the pdf.
This leads to some empty folders in the output folder + subfolders including images which are not needed.
Is there a way to avoid this behaviour?

**Comment by abelsromero** [comment]
> Is there a way to avoid this behaviour?

By default everything is considered a resource and is copied, but you can set it to exclude them all.

```xml
        <resources>
            <resource>
                <directory>.</directory>
                <excludes>
                    <exclude>**/**</exclude>
                </excludes>
            </resource>
        </resources>
```

**Comment by marceloverdijk** [comment]
Thanks a lot, that helped.
