### ISSUE TITLE
Explore enforcer as extension

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#613]
**What is this issue about?**

- [ ] Bug report
- [ ] Feature request
- [ ] Question
- [x] Research, maybe end up in a feature

**Description**
Maven enforcer in recent versions is presented as an extension and not as a plugin. We can have a look and see what benefits we get from it and especially check when the plugin is going out of support.
https://maven.apache.org/enforcer/maven-enforcer-extension/

**Comment by khmarbaise** [comment]
Can you write what brought you to the conclusion that a plugin is going out of support?
