### ISSUE TITLE
Integration with Maven Site Plugin: document title is not set

### ISSUE THREAD

**Issue by raoulvdberge** [asciidoctor/asciidoctor-maven-plugin#739]
Thank you for taking your time to talk with us!

**What is this issue about?**

- [ ] Bug report
- [x] Feature request
- [ ] Question

**Description**

I have Asciidoc documents that  I'm loading into a Maven site.

However, the HTML page title is always empty, in the form of "site name - ". It seems to ignore the document title.

How can I make it use the document title?

This is my maven config:

```
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.12.1</version>
                <configuration>
                    <generateReports>false</generateReports>
                    <generateSitemap>true</generateSitemap>
                    <relativizeDecorationLinks>false</relativizeDecorationLinks>
                    <locales>en</locales>
                    <inputEncoding>UTF-8</inputEncoding>
                    <outputEncoding>UTF-8</outputEncoding>
                    <asciidoc>
                        <attributes>
                            <source-highlighter>coderay</source-highlighter>
                            <coderay-css>style</coderay-css>
                        </attributes>
                    </asciidoc>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctor-maven-plugin</artifactId>
                        <version>2.2.4</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```

**Environment information**

* asciidoctor-maven-plugin version: 2.2.4
* asciidoctorj version: not set, default bundled with 2.2.4

* Maven, Java and OS version: 
```
Java version: 17.0.9, vendor: Eclipse Adoptium, runtime: .jdks\temurin-17.0.9
Default locale: nl_BE, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by abelsromero** [comment]
Not sure I understand, each document title should appear on the page as seen in the examples

![image](https://github.com/asciidoctor/asciidoctor-maven-plugin/assets/5781153/b1955f35-8bfd-4986-bbcc-44874b9d8e0e)

On top of that, there's the site title, which comes from the pom's project name.

**Comment by abelsromero** [comment]
Btw, I was planning to release v3.0.0 soon-ish :tm: and that provides a new maven-site module that offers a better out of the box experience, no need to add custom CSS. If that's your goal maybe you want to give it a try?

**Comment by abelsromero** [comment]
> I meant the html page title, between the `<title>` tags. It doesn't seem to put the asciidoc document title there.

The module [embeds the page without headers](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/80c699035933aae133afaf9592bcc065c3d41b74/src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParser.java#L88). The the menu/toc, top section and meta are handled by maven-site, not asciidoctor. 
The [interface](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/80c699035933aae133afaf9592bcc065c3d41b74/src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParser.java#L48) does not provide a way to customize meta, but it's something we could discuss with the maven team.

**Comment by abelsromero** [comment]
It seems something similar was discussed some time ago but went stale https://issues.apache.org/jira/browse/DOXIA-471?jql=project%20%3D%20%22Maven%20Doxia%22%20AND%20text%20~%20title. Before re-opening it'd be good to do some extra research, maven-site team is working on a new major, so it's the time to propose breaking changes.

**Comment by abelsromero** [comment]
I saw this feature was fixed with https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/763.
Now the `title` is set as "${title} - ${project name}", note the project name is appended automatically by Doxia.

![image](https://github.com/user-attachments/assets/f443aaf4-8db7-4d2b-be97-0ebafc7e2896)
